In [1]:
import sklearn
import scipy 
import numpy as np
import pandas as pd
import os
import sys

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "0"
sys.path.append(os.path.abspath("src"))
import jdcoot

sourceDomainName = ['amazon'] #['caltech10','amazon','webcam']
targetDomainName = ['amazon'] #['caltech10','amazon','webcam']

tests = []
data_source = {}
data_target = {}

min_max_scaler = sklearn.preprocessing.MinMaxScaler()
# Collab
possible_data = scipy.io.loadmat('caltech10_caffe.mat')
feat = possible_data['fts'].astype(float)
labels = possible_data['labels'].ravel()
S_data = [feat, labels]
S_nClass = len(np.unique(labels)) # nb de class in source data
possible_data = scipy.io.loadmat('caltech10_google.mat')
feat = possible_data['fts'].astype(float)
labels = possible_data['labels'].ravel()
T_data = [feat, labels]
T_nClass = len(np.unique(labels)) # nb de class in target data

source=pd.DataFrame(np.concatenate((S_data[0],S_data[1].reshape(-1,1)),axis=1),columns=['X'+str(i) for i in range(S_data[0].shape[1])]+['Z'])
target=pd.DataFrame(np.concatenate((T_data[0],T_data[1].reshape(-1,1)),axis=1),columns=['X'+str(i) for i in range(T_data[0].shape[1])]+['Z'])

source.loc[:,'Z'] = source.loc[:, 'Z'] - 1
target.loc[:,'Z'] = target.loc[:, 'Z'] - 1

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1766671149.000880 2883090 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1766671149.006032 2883090 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered

In [13]:
def get_data(x, y, nbtrain, nbtest, nseed):
 
    y = y.ravel()
    n = x.shape[0]

    if nbtrain + nbtest > n:
        raise ValueError("nbtrain + nbtest exceeds total number of samples")

    np.random.seed(nseed)
    idx = np.random.permutation(n)

    train_idx = idx[:nbtrain]
    test_idx = idx[nbtrain:nbtrain + nbtest]

    xtrain = x[train_idx]
    ytrain = y[train_idx]

    xtest = x[test_idx]
    ytest = y[test_idx]

    return xtrain, ytrain, xtest, ytest

In [5]:
from jdcoot.models.discrete_unsupervised_jdcoot import discrete_unsupervised_jdcoot
from jdcoot.models.discrete_semisupervised_jdcoot import discrete_semisupervised_jdcoot
from jdcoot.models.discrete_partial_jdcoot import discrete_partial_jdcoot
from jdcoot.models.discrete_unsupervised_coot import discrete_unsupervised_coot
from jdcoot.models.discrete_semisupervised_coot import discrete_semisupervised_coot
from jdcoot.models.discrete_partial_coot import discrete_partial_coot
from jdcoot.models.discrete_semisupervised_reference import discrete_semisupervised_reference
from jdcoot.models.discrete_partial_reference import discrete_partial_reference

In [6]:
import numpy as np
nbtrain=80
nbtest=20
XtotS = np.array(S_data[0], dtype=float)
YtotS = np.array(S_data[1], dtype=int).reshape(-1, 1) - 1
XtotT = np.array(T_data[0], dtype=float)
YtotT = np.array(T_data[1], dtype=int).reshape(-1, 1) - 1
repe = 1

XS1,yS1,XStest,yStest = get_data(XtotS,YtotS,nbtrain,nbtest,repe)
XT1,yT1,XTtest,yTtest = get_data(XtotT,YtotT,nbtrain,nbtest,repe)

    #XS, yS = generateSubset(XS1, yS1, perClassSource)
    #XT, yT = generateSubset(XT1, yT1, perClassSource)
S = pd.DataFrame(np.c_[XS1, yS1],
                     columns=['X' + str(i) for i in range(XS1.shape[1])] + ['Z'])
T = pd.DataFrame(np.c_[XT1, yT1],
                     columns=['X' + str(i) for i in range(XT1.shape[1])] + ['Z'])
S_test = pd.DataFrame(np.c_[XStest, yStest],
                          columns=['X' + str(i) for i in range(XStest.shape[1])] + ['Z'])
T_test = pd.DataFrame(np.c_[XTtest, yTtest],
                          columns=['X' + str(i) for i in range(XTtest.shape[1])] + ['Z'])


# Exemple de valeurs à tester pour alpha
alpha_values = np.arange(0, 4.01, 0.5)   # 0, 0.1, 0.2, ..., 1.0
best_alpha = None
best_score = -np.inf  # ou 0 selon ta métrique

for a in alpha_values:

    pure_source, pure_target, test_source, test_target = discrete_unsupervised_jdcoot(source, target, source, target, alpha=a)

    score = test_target  
    
    if score > best_score:
        best_score = score
        best_alpha = a

print("Meilleur alpha :", best_alpha)
print("Score associé :", best_score)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]

I0000 00:00:1766671343.394051 2883090 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 470 MB memory:  -> device: 0, name: Tesla V100S-PCIE-32GB, pci bus id: 0000:3b:00.0, compute capability: 7.0
I0000 00:00:1766671345.275930 2883470 service.cc:148] XLA service 0x70d5fdc852d0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1766671345.275968 2883470 service.cc:156]   StreamExecutor device (0): Tesla V100S-PCIE-32GB, Compute Capability 7.0
I0000 00:00:1766671345.293814 2883470 cuda_dnn.cc:529] Loaded cuDNN version 91002
I0000 00:00:1766671345.399102 2883470 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.

Delta: 0.020255819472126384 	  Loss: 2.199211259965066 	 Accuracy: 0.13446126447016918
Delta: 0.014972405370403894 	  Loss: 2.1989955211938463 	 Accuracy: 0.13446126447016918
Delta: 0.016612462978308498 	  Loss: 2.1988846700056266 	 Accuracy: 0.13446126447016918
Delta: 0.018277356241225073 	  Loss: 2.19829457870092 	 Accuracy: 0.13535173642030277
Delta: 0.016763675094514454 	  Loss: 2.197712264507718 	 Accuracy: 0.13446126447016918
Delta: 0.015597660987935351 	  Loss: 2.196560733370316 	 Accuracy: 0.12644701691896706
Delta: 0.0147186626428934 	  Loss: 2.194574724254459 	 Accuracy: 0.12288512911843277
Delta: 0.01476511939470042 	  Loss: 2.1915773402157965 	 Accuracy: 0.1246660730186999
Delta: 0.014139803653254214 	  Loss: 2.188527905220483 	 Accuracy: 0.12644701691896706
Delta: 0.014880333420051975 	  Loss: 2.184547622187754 	 Accuracy: 0.12288512911843277
Delta: 0.02046712018303437 	  Loss: 2.1711045277850944 	 Accuracy: 0.26714158504007124
Delta: 0.017466784970962126 	  Loss: 2.118946208368037 	 Accuracy: 0.3250222617987533
Delta: 0.01623914550918635 	  Loss: 2.0438691936429576 	 Accuracy: 0.371326803205699
Delta: 0.016761525069657692 	  Loss: 1.9426971657103989 	 Accuracy: 0.4568121104185218
Delta: 0.016060048152491884 	  Loss: 1.809587862533309 	 Accuracy: 0.4781834372217275
Delta: 0.013023996123627249 	  Loss: 1.712291531475402 	 Accuracy: 0.4764024933214604
Delta: 0.010281658644979996 	  Loss: 1.6711605366012294 	 Accuracy: 0.4568121104185218
Delta: 0.00936865498480531 	  Loss: 1.6532951922814967 	 Accuracy: 0.4514692787177204
Delta: 0.007879614812742743 	  Loss: 1.644192382040911 	 Accuracy: 0.4479073909171861

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.006826229221174854 	  Loss: 1.6394072717302222 	 Accuracy: 0.4479073909171861
Delta: 0.021139936869476135 	  Loss: 2.137720937774647 	 Accuracy: 0.26714158504007124
Delta: 0.018736876034559705 	  Loss: 2.018295786905181 	 Accuracy: 0.3241317898486198
Delta: 0.017710603639086248 	  Loss: 1.894115937623849 	 Accuracy: 0.3187889581478183
Delta: 0.016580472440510082 	  Loss: 1.7732711848495075 	 Accuracy: 0.26981300089047194
Delta: 0.013856616388424252 	  Loss: 1.7025737753070458 	 Accuracy: 0.27960819234194123
Delta: 0.011297688200365173 	  Loss: 1.667787588736679 	 Accuracy: 0.28138913624220835
Delta: 0.008083394717144893 	  Loss: 1.651907154182398 	 Accuracy: 0.2965271593944791

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.0074299607957087 	  Loss: 1.6447720694067238 	 Accuracy: 0.2920747996438112
Delta: 0.006295716179489466 	  Loss: 1.6405308781478398 	 Accuracy: 0.2991985752448798
Delta: 0.0050219067549009296 	  Loss: 1.6391793426829588 	 Accuracy: 0.3009795191451469
Delta: 0.021387331026680494 	  Loss: 2.1039250091307604 	 Accuracy: 0.30632235084594833
Delta: 0.01953760155387033 	  Loss: 1.916364901287567 	 Accuracy: 0.3330365093499555
Delta: 0.01777302228509095 	  Loss: 1.7475649671922193 	 Accuracy: 0.2769367764915405
Delta: 0.014130911664225924 	  Loss: 1.6682441116748483 	 Accuracy: 0.25823686553873554
Delta: 0.011030751946604626 	  Loss: 1.637206136678612 	 Accuracy: 0.25645592163846836
Delta: 0.009229456690045124 	  Loss: 1.623349701814865 	 Accuracy: 0.26090828138913624
Delta: 0.0073699225457281164 	  Loss: 1.6178307922571205 	 Accuracy: 0.26357969723953695

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.005331800810240427 	  Loss: 1.615773414844976 	 Accuracy: 0.26447016918967053
Delta: 0.004209809477839755 	  Loss: 1.6150445957214576 	 Accuracy: 0.26268922528940336
Delta: 0.0033815696409950514 	  Loss: 1.6149366115803043 	 Accuracy: 0.26090828138913624
Delta: 0.021637972048714017 	  Loss: 2.071424567899002 	 Accuracy: 0.30365093499554763
Delta: 0.019125069301036204 	  Loss: 1.890743289104198 	 Accuracy: 0.37043633125556547
Delta: 0.018247347399881538 	  Loss: 1.7465551756254427 	 Accuracy: 0.3232413178984862
Delta: 0.01475983747148114 	  Loss: 1.6773785930016314 	 Accuracy: 0.29385574354407834
Delta: 0.011523146887829428 	  Loss: 1.650814372865005 	 Accuracy: 0.2947462154942119
Delta: 0.009203654884079577 	  Loss: 1.6402767726214835 	 Accuracy: 0.2956366874443455

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.008552633667250654 	  Loss: 1.6342849275239422 	 Accuracy: 0.2965271593944791
Delta: 0.006432587605354563 	  Loss: 1.6323605734010178 	 Accuracy: 0.2983081032947462
Delta: 0.004652916458728443 	  Loss: 1.6309991520921152 	 Accuracy: 0.3045414069456812
Delta: 0.003935013451654303 	  Loss: 1.630665170122651 	 Accuracy: 0.3018699910952805
Delta: 0.021815938143511827 	  Loss: 2.043832949939135 	 Accuracy: 0.3178984861976848
Delta: 0.019687691778164748 	  Loss: 1.8405457370234513 	 Accuracy: 0.3811219946571683
Delta: 0.018123821026743266 	  Loss: 1.7026698202551642 	 Accuracy: 0.3437221727515583
Delta: 0.014388972823181743 	  Loss: 1.6483313074448431 	 Accuracy: 0.333926981300089
Delta: 0.010871738565551244 	  Loss: 1.6309206710580715 	 Accuracy: 0.3321460373998219
Delta: 0.009403091942438806 	  Loss: 1.6237253580881332 	 Accuracy: 0.340160284951024

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.007620796517852414 	  Loss: 1.6200659708677607 	 Accuracy: 0.3330365093499555
Delta: 0.0065508395086700385 	  Loss: 1.6183120034721217 	 Accuracy: 0.3330365093499555
Delta: 0.0035088174397648712 	  Loss: 1.6178563742777254 	 Accuracy: 0.3303650934995548
Delta: 0.0024185825318021256 	  Loss: 1.6179491488961841 	 Accuracy: 0.3312555654496883
Delta: 0.021978468320414207 	  Loss: 2.019684586612796 	 Accuracy: 0.3357079252003562
Delta: 0.019562175924977977 	  Loss: 1.824978761290553 	 Accuracy: 0.371326803205699
Delta: 0.017379418847890016 	  Loss: 1.7159905722138347 	 Accuracy: 0.383793410507569
Delta: 0.015164160396925266 	  Loss: 1.6608978922914532 	 Accuracy: 0.3757791629563669
Delta: 0.011743136584474064 	  Loss: 1.6392573421538625 	 Accuracy: 0.36776491540516476
Delta: 0.009769934637272742 	  Loss: 1.6303363537631896 	 Accuracy: 0.37043633125556547

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.007638857545539232 	  Loss: 1.6257685200016572 	 Accuracy: 0.37310774710596617
Delta: 0.005525722632387978 	  Loss: 1.6241537593097464 	 Accuracy: 0.37043633125556547
Delta: 0.00374940237771424 	  Loss: 1.6239403880957015 	 Accuracy: 0.3686553873552983
Delta: 0.003058994887425734 	  Loss: 1.6237648146402972 	 Accuracy: 0.371326803205699
Delta: 0.0220973439479129 	  Loss: 1.9964673159307165 	 Accuracy: 0.30365093499554763
Delta: 0.019815837289312254 	  Loss: 1.7949485878888929 	 Accuracy: 0.3374888691006233
Delta: 0.017897947391871956 	  Loss: 1.694430712256594 	 Accuracy: 0.3472840605520926
Delta: 0.016110216971803655 	  Loss: 1.6281937729768403 	 Accuracy: 0.3757791629563669
Delta: 0.012987572504798657 	  Loss: 1.5932155022413415 	 Accuracy: 0.39893143365983974

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.010111762506248602 	  Loss: 1.5770684661027898 	 Accuracy: 0.41317898486197685
Delta: 0.007587831116163659 	  Loss: 1.5700147212944815 	 Accuracy: 0.41585040071237755
Delta: 0.006114985820372909 	  Loss: 1.567513164001266 	 Accuracy: 0.42030276046304543
Delta: 0.0034558219764672824 	  Loss: 1.5668947295298303 	 Accuracy: 0.41763134461264473
Delta: 0.0034600777730345355 	  Loss: 1.5668601274436522 	 Accuracy: 0.42119323241317896
Delta: 0.022209662152709617 	  Loss: 1.9783352838166608 	 Accuracy: 0.2983081032947462
Delta: 0.01981198219667149 	  Loss: 1.775316320730719 	 Accuracy: 0.352626892252894
Delta: 0.017857247557752275 	  Loss: 1.6787291043054673 	 Accuracy: 0.3196794300979519
Delta: 0.015436910081205941 	  Loss: 1.6265487505012168 	 Accuracy: 0.3383793410507569
Delta: 0.012759139109492204 	  Loss: 1.6012059299300674 	 Accuracy: 0.35529830810329477
Delta: 0.011393700648149865 	  Loss: 1.5851322571790973 	 Accuracy: 0.3686553873552983

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.010151245910680881 	  Loss: 1.5745233338441849 	 Accuracy: 0.3722172751558326
Delta: 0.007808550765554239 	  Loss: 1.5698424576119827 	 Accuracy: 0.3748886910062333
Delta: 0.005566732322717676 	  Loss: 1.5682890961790332 	 Accuracy: 0.3757791629563669
Delta: 0.0040376089322940135 	  Loss: 1.5679172377800326 	 Accuracy: 0.377560106856634
Meilleur alpha : 0.5
Score associé : 0.4479073909171861

In [14]:
results = []
numRepetitions = 10
nbtrain = 800
nbtest = 200
a = 0.4

prop_target_values_s = [0.01, 0.05, 0.1, 0.2, 0.4]
prop_target_values_p = [0.01, 0.05, 0.1, 0.2, 0.4]

XtotS = np.array(S_data[0], dtype=float)
YtotS = np.array(S_data[1], dtype=int).reshape(-1, 1) - 1

XtotT = np.array(T_data[0], dtype=float)
YtotT = np.array(T_data[1], dtype=int).reshape(-1, 1) - 1

for repe in range(numRepetitions):
    print("num repe :", repe + 1)

    XS1, yS1, XStest, yStest = get_data(XtotS, YtotS, nbtrain, nbtest, repe)
    XT1, yT1, XTtest, yTtest = get_data(XtotT, YtotT, nbtrain, nbtest, repe)

    S = pd.DataFrame(
        np.c_[XS1, yS1],
        columns=[f"X{i}" for i in range(XS1.shape[1])] + ["Z"]
    )

    T = pd.DataFrame(
        np.c_[XT1, yT1],
        columns=[f"X{i}" for i in range(XT1.shape[1])] + ["Z"]
    )

    S_test = pd.DataFrame(
        np.c_[XStest, yStest],
        columns=[f"X{i}" for i in range(XStest.shape[1])] + ["Z"]
    )

    T_test = pd.DataFrame(
        np.c_[XTtest, yTtest],
        columns=[f"X{i}" for i in range(XTtest.shape[1])] + ["Z"]
    )

    # =========================================================
    # UNSUPERVISED
    # =========================================================
     # COOT
    pure_source, pure_target, test_source, test_target = \
        discrete_unsupervised_coot(S, T, S_test, T_test)

    results.append({
        "repetition": repe,
        "recoding": "coot",
        "learning": "unsupervised",
        "prop_source": 1,
        "prop_target": 0,
        "pure_source": pure_source,
        "test_source": test_source,
        "pure_target": pure_target,
        "test_target": test_target,
    })
    
    # JDCOOT
    pure_source, pure_target, test_source, test_target = \
        discrete_unsupervised_jdcoot(S, T, S_test, T_test, alpha=a)

    results.append({
        "repetition": repe,
        "recoding": "jdcoot",
        "learning": "unsupervised",
        "prop_source": 1,
        "prop_target": 0,
        "pure_source": pure_source,
        "test_source": test_source,
        "pure_target": pure_target,
        "test_target": test_target,
    })

   
import pandas as pd

df_results = pd.DataFrame(results)


df_results

df_summary = (
    df_results
    .groupby(
        ["recoding", "learning", "prop_source", "prop_target"],
        as_index=False
    )
    .agg(
        pure_source_mean=("pure_source", "mean"),
        pure_source_var=("pure_source", "var"),
        test_source_mean=("test_source", "mean"),
        test_source_var=("test_source", "var"),
        pure_target_mean=("pure_target", "mean"),
        pure_target_var=("pure_target", "var"),
        test_target_mean=("test_target", "mean"),
        test_target_var=("test_target", "var"),
    )
)

df_summary

num repe : 1
Delta:       0.0156359 	 Loss:       2.2001753

Delta:       0.0208151 	 Loss:       2.1664660
Delta:       0.0177443 	 Loss:       2.1378616
Delta:       0.0151617 	 Loss:       2.1216158
Delta:       0.0132620 	 Loss:       2.1119749
Delta:       0.0116932 	 Loss:       2.1051573
Delta:       0.0090593 	 Loss:       2.1014896
Delta:       0.0063191 	 Loss:       2.1005522
Delta:       0.0048636 	 Loss:       2.1002913
Delta:       0.0031599 	 Loss:       2.1001825
Delta:       0.0031378 	 Loss:       2.1002385
Delta:       0.0032486 	 Loss:       2.1002115
Delta:       0.0016972 	 Loss:       2.1001982
Delta:       0.0021360 	 Loss:       2.1001601
Delta:       0.0014302 	 Loss:       2.1001308
Delta:       0.0010391 	 Loss:       2.1001257
Delta:       0.0000011 	 Loss:       2.1001270
Delta:       0.0000000 	 Loss:       2.1001270
converged at iter  17
Delta: 0.020565340734303172 	  Loss: 2.179369831981312 	 Accuracy: 0.2475
Delta: 0.017793093734844667 	  Loss: 2.1362575883056776 	 Accuracy: 0.2675
Delta: 0.01691620669720565 	  Loss: 2.0626519488698283 	 Accuracy: 0.32625
Delta: 0.016812897359696318 	  Loss: 1.935333486938806 	 Accuracy: 0.39875
Delta: 0.014573427152632776 	  Loss: 1.8054074906950413 	 Accuracy: 0.40375
Delta: 0.012414185182031997 	  Loss: 1.7310521838359583 	 Accuracy: 0.425
Delta: 0.011452834537332658 	  Loss: 1.692362938850221 	 Accuracy: 0.42125
Delta: 0.010359685500936284 	  Loss: 1.6701496905163726 	 Accuracy: 0.435
Delta: 0.00892322005149982 	  Loss: 1.6566170199333232 	 Accuracy: 0.43375
Delta: 0.0076332165627193745 	  Loss: 1.6492323725064955 	 Accuracy: 0.44
num repe : 2
Delta:       0.0156352 	 Loss:       2.2114827
Delta:       0.0207905 	 Loss:       2.1776097
Delta:       0.0175293 	 Loss:       2.1501197
Delta:       0.0145295 	 Loss:       2.1371733
Delta:       0.0143840 	 Loss:       2.1267720
Delta:       0.0147303 	 Loss:       2.1109830
Delta:       0.0140007 	 Loss:       2.0904948
Delta:       0.0111559 	 Loss:       2.0792493
Delta:       0.0077363 	 Loss:       2.0763177
Delta:       0.0050162 	 Loss:       2.0757680
Delta:       0.0040699 	 Loss:       2.0755470
Delta:       0.0015123 	 Loss:       2.0755315
Delta:       0.0009161 	 Loss:       2.0755305
Delta:       0.0004901 	 Loss:       2.0755274
Delta:       0.0000003 	 Loss:       2.0755274
converged at iter  14
Delta: 0.020596488608883533 	  Loss: 2.1899986970382663 	 Accuracy: 0.2375
Delta: 0.01806037951251494 	  Loss: 2.1467981941617014 	 Accuracy: 0.3175
Delta: 0.01647240456686527 	  Loss: 2.0800852991306877 	 Accuracy: 0.395
Delta: 0.01575707925570861 	  Loss: 1.9823646278368041 	 Accuracy: 0.4225
Delta: 0.013931121640076273 	  Loss: 1.881507907564624 	 Accuracy: 0.41625
Delta: 0.012491057196941002 	  Loss: 1.8106757802034479 	 Accuracy: 0.42125
Delta: 0.011468175259015306 	  Loss: 1.772630185346435 	 Accuracy: 0.40375
Delta: 0.010208499079438986 	  Loss: 1.755430374092748 	 Accuracy: 0.3875
Delta: 0.009572261743512759 	  Loss: 1.7474579446067875 	 Accuracy: 0.385

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.008673582956440289 	  Loss: 1.743111702832529 	 Accuracy: 0.38125
num repe : 3
Delta:       0.0156356 	 Loss:       2.1923470
Delta:       0.0207089 	 Loss:       2.1577418
Delta:       0.0176410 	 Loss:       2.1315526
Delta:       0.0147688 	 Loss:       2.1184375
Delta:       0.0121449 	 Loss:       2.1107606
Delta:       0.0106553 	 Loss:       2.1056453
Delta:       0.0087416 	 Loss:       2.1032827
Delta:       0.0086679 	 Loss:       2.1020481
Delta:       0.0090215 	 Loss:       2.1006614
Delta:       0.0097421 	 Loss:       2.0981950
Delta:       0.0086315 	 Loss:       2.0954841
Delta:       0.0070036 	 Loss:       2.0940530
Delta:       0.0049179 	 Loss:       2.0933799
Delta:       0.0033443 	 Loss:       2.0930857
Delta:       0.0037750 	 Loss:       2.0930008
Delta:       0.0015891 	 Loss:       2.0928823
Delta:       0.0000005 	 Loss:       2.0928823
converged at iter  16
Delta: 0.02049267782605962 	  Loss: 2.1700797414482245 	 Accuracy: 0.23375
Delta: 0.01845189952142108 	  Loss: 2.118797011462033 	 Accuracy: 0.275
Delta: 0.017254898631652638 	  Loss: 2.0079662109629277 	 Accuracy: 0.46875
Delta: 0.015238443086039256 	  Loss: 1.8847642074060034 	 Accuracy: 0.47625
Delta: 0.013227390655918632 	  Loss: 1.7986695954032095 	 Accuracy: 0.445
Delta: 0.012070204726853823 	  Loss: 1.7474643262203018 	 Accuracy: 0.41375
Delta: 0.011057618795869984 	  Loss: 1.7172094656106862 	 Accuracy: 0.39875
Delta: 0.010228137614592852 	  Loss: 1.699172755328818 	 Accuracy: 0.385
Delta: 0.010058481532229314 	  Loss: 1.6878812514642432 	 Accuracy: 0.3825
Delta: 0.009377237073953635 	  Loss: 1.6804577575383575 	 Accuracy: 0.38125
num repe : 4
Delta:       0.0156354 	 Loss:       2.2036628
Delta:       0.0206319 	 Loss:       2.1713215
Delta:       0.0176953 	 Loss:       2.1448381
Delta:       0.0159788 	 Loss:       2.1261484
Delta:       0.0142194 	 Loss:       2.1102172
Delta:       0.0096923 	 Loss:       2.1041904
Delta:       0.0063016 	 Loss:       2.1030449
Delta:       0.0039977 	 Loss:       2.1027413
Delta:       0.0039028 	 Loss:       2.1025828
Delta:       0.0031365 	 Loss:       2.1024788
Delta:       0.0040945 	 Loss:       2.1024264
Delta:       0.0053169 	 Loss:       2.1022852
Delta:       0.0064043 	 Loss:       2.1019947
Delta:       0.0071019 	 Loss:       2.1012358
Delta:       0.0073600 	 Loss:       2.1005883
Delta:       0.0059629 	 Loss:       2.1001612
Delta:       0.0053916 	 Loss:       2.0996502
Delta:       0.0032715 	 Loss:       2.0994904
Delta:       0.0027907 	 Loss:       2.0994387
Delta:       0.0026142 	 Loss:       2.0994005
Delta:       0.0021611 	 Loss:       2.0993823
Delta:       0.0000017 	 Loss:       2.0993789
Delta:       0.0000000 	 Loss:       2.0993789
converged at iter  22
Delta: 0.020621602293596608 	  Loss: 2.18277947339166 	 Accuracy: 0.25125
Delta: 0.018367379744249616 	  Loss: 2.1391482813998524 	 Accuracy: 0.29
Delta: 0.017114250613419778 	  Loss: 2.044632782619617 	 Accuracy: 0.4325
Delta: 0.01582977166371514 	  Loss: 1.9115731258166737 	 Accuracy: 0.47625
Delta: 0.013924224242584918 	  Loss: 1.807682448778599 	 Accuracy: 0.5025
Delta: 0.0131126042284756 	  Loss: 1.741148715332046 	 Accuracy: 0.5125
Delta: 0.012166643897505809 	  Loss: 1.696189936033624 	 Accuracy: 0.525
Delta: 0.010603950288555741 	  Loss: 1.6678211881738194 	 Accuracy: 0.5275
Delta: 0.00933320244793274 	  Loss: 1.651329533111645 	 Accuracy: 0.545
Delta: 0.008118776122112006 	  Loss: 1.6427200573833773 	 Accuracy: 0.54
num repe : 5
Delta:       0.0156362 	 Loss:       2.1999468
Delta:       0.0208641 	 Loss:       2.1668258
Delta:       0.0183232 	 Loss:       2.1223468
Delta:       0.0134387 	 Loss:       2.1016983
Delta:       0.0092818 	 Loss:       2.0975899
Delta:       0.0069098 	 Loss:       2.0959352
Delta:       0.0053479 	 Loss:       2.0955114
Delta:       0.0039490 	 Loss:       2.0953590
Delta:       0.0041970 	 Loss:       2.0952313
Delta:       0.0029398 	 Loss:       2.0952003
Delta:       0.0027044 	 Loss:       2.0951346
Delta:       0.0011506 	 Loss:       2.0950898
Delta:       0.0020473 	 Loss:       2.0950425
Delta:       0.0019864 	 Loss:       2.0950353
Delta:       0.0022146 	 Loss:       2.0950391
Delta:       0.0016610 	 Loss:       2.0950230
Delta:       0.0014676 	 Loss:       2.0950149
Delta:       0.0035596 	 Loss:       2.0950020
Delta:       0.0041089 	 Loss:       2.0949401
Delta:       0.0043627 	 Loss:       2.0948960
Delta:       0.0050028 	 Loss:       2.0947837
Delta:       0.0052288 	 Loss:       2.0946316
Delta:       0.0067828 	 Loss:       2.0943527
Delta:       0.0084284 	 Loss:       2.0935178
Delta:       0.0095940 	 Loss:       2.0922336
Delta:       0.0113602 	 Loss:       2.0887980
Delta:       0.0115510 	 Loss:       2.0812402
Delta:       0.0090041 	 Loss:       2.0759276
Delta:       0.0056950 	 Loss:       2.0747069
Delta:       0.0022254 	 Loss:       2.0745028
Delta:       0.0028765 	 Loss:       2.0744913
Delta:       0.0012517 	 Loss:       2.0744240
Delta:       0.0000004 	 Loss:       2.0744240
converged at iter  32
Delta: 0.020544616396266764 	  Loss: 2.1791111815873694 	 Accuracy: 0.2425
Delta: 0.018471840530870202 	  Loss: 2.1291567044873245 	 Accuracy: 0.17625
Delta: 0.01661155113211245 	  Loss: 2.0371822545015443 	 Accuracy: 0.23125
Delta: 0.015387250348333497 	  Loss: 1.930763983386242 	 Accuracy: 0.34875
Delta: 0.014187270541295875 	  Loss: 1.8407903275637754 	 Accuracy: 0.395
Delta: 0.013256249796924312 	  Loss: 1.770923394306424 	 Accuracy: 0.3825
Delta: 0.01235307578665508 	  Loss: 1.7239687841979705 	 Accuracy: 0.36
Delta: 0.01069897090230486 	  Loss: 1.6983448399814427 	 Accuracy: 0.35125
Delta: 0.008523592169289896 	  Loss: 1.6846515517913234 	 Accuracy: 0.34875

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.008247314531444117 	  Loss: 1.6775618628425595 	 Accuracy: 0.355
num repe : 6
Delta:       0.0156355 	 Loss:       2.2109147
Delta:       0.0207343 	 Loss:       2.1771600
Delta:       0.0184680 	 Loss:       2.1330008
Delta:       0.0135989 	 Loss:       2.1090764
Delta:       0.0103890 	 Loss:       2.1033672
Delta:       0.0083398 	 Loss:       2.1008587
Delta:       0.0077078 	 Loss:       2.0996038
Delta:       0.0069521 	 Loss:       2.0984724
Delta:       0.0062779 	 Loss:       2.0979292
Delta:       0.0053576 	 Loss:       2.0974928
Delta:       0.0052674 	 Loss:       2.0969779
Delta:       0.0041287 	 Loss:       2.0967477
Delta:       0.0039315 	 Loss:       2.0966034
Delta:       0.0018689 	 Loss:       2.0965478
Delta:       0.0025439 	 Loss:       2.0965145
Delta:       0.0008489 	 Loss:       2.0965070
Delta:       0.0000001 	 Loss:       2.0965069
converged at iter  16
Delta: 0.020478070540851392 	  Loss: 2.1894515929843807 	 Accuracy: 0.29625
Delta: 0.017853373937505895 	  Loss: 2.1446557600041736 	 Accuracy: 0.31
Delta: 0.015439122703466103 	  Loss: 2.0725882813938146 	 Accuracy: 0.285
Delta: 0.015102544181407567 	  Loss: 1.9860596364549534 	 Accuracy: 0.26
Delta: 0.01496359874252521 	  Loss: 1.908970164303787 	 Accuracy: 0.23375
Delta: 0.014683924386263017 	  Loss: 1.850518255382418 	 Accuracy: 0.2075
Delta: 0.014166745806993392 	  Loss: 1.8022489938052375 	 Accuracy: 0.2
Delta: 0.01236843845417006 	  Loss: 1.7661753439071624 	 Accuracy: 0.19875
Delta: 0.009774389532471893 	  Loss: 1.745309655440952 	 Accuracy: 0.1925
Delta: 0.00873107296836651 	  Loss: 1.7346067848660236 	 Accuracy: 0.1925
num repe : 7
Delta:       0.0156356 	 Loss:       2.1927973
Delta:       0.0207590 	 Loss:       2.1589625
Delta:       0.0184680 	 Loss:       2.1219603
Delta:       0.0162604 	 Loss:       2.0798126
Delta:       0.0119893 	 Loss:       2.0646149
Delta:       0.0083457 	 Loss:       2.0611119
Delta:       0.0042675 	 Loss:       2.0603016
Delta:       0.0022733 	 Loss:       2.0602039
Delta:       0.0009180 	 Loss:       2.0601857
Delta:       0.0004897 	 Loss:       2.0601840
Delta:       0.0004889 	 Loss:       2.0601841
converged at iter  10
Delta: 0.020514911085448097 	  Loss: 2.1714455668989094 	 Accuracy: 0.28125
Delta: 0.01864462885204558 	  Loss: 2.1192700670681592 	 Accuracy: 0.345
Delta: 0.017002440550435795 	  Loss: 2.011912459237373 	 Accuracy: 0.41125
Delta: 0.014443987413766707 	  Loss: 1.8997675454620815 	 Accuracy: 0.495
Delta: 0.01412917193287922 	  Loss: 1.8103171585576807 	 Accuracy: 0.51
Delta: 0.01306000712736683 	  Loss: 1.728109792354711 	 Accuracy: 0.5475
Delta: 0.011561759674008546 	  Loss: 1.6698441200325083 	 Accuracy: 0.55875
Delta: 0.009450688172037973 	  Loss: 1.6399399044743748 	 Accuracy: 0.56375
Delta: 0.008333022721113564 	  Loss: 1.6278811021125552 	 Accuracy: 0.565

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.006721993869176708 	  Loss: 1.6236493389606959 	 Accuracy: 0.5675
num repe : 8
Delta:       0.0156361 	 Loss:       2.1946524
Delta:       0.0206580 	 Loss:       2.1611749
Delta:       0.0181739 	 Loss:       2.1300223
Delta:       0.0154619 	 Loss:       2.1003057
Delta:       0.0127411 	 Loss:       2.0870107
Delta:       0.0099782 	 Loss:       2.0821693
Delta:       0.0073979 	 Loss:       2.0802177
Delta:       0.0051541 	 Loss:       2.0797177
Delta:       0.0041000 	 Loss:       2.0795023
Delta:       0.0009220 	 Loss:       2.0794279
Delta:       0.0000011 	 Loss:       2.0794264
Delta:       0.0000000 	 Loss:       2.0794264
converged at iter  11
Delta: 0.02054709504447819 	  Loss: 2.1731389591884422 	 Accuracy: 0.2525
Delta: 0.018293940348774296 	  Loss: 2.121391941053391 	 Accuracy: 0.29875
Delta: 0.016477123391664964 	  Loss: 2.0237526111005 	 Accuracy: 0.32625
Delta: 0.015234479061259305 	  Loss: 1.9063114269336152 	 Accuracy: 0.2925
Delta: 0.013788258327846711 	  Loss: 1.8132038158951387 	 Accuracy: 0.23875
Delta: 0.012551930486632553 	  Loss: 1.7507965840718929 	 Accuracy: 0.23
Delta: 0.011322092039971586 	  Loss: 1.7113259536498338 	 Accuracy: 0.22375
Delta: 0.01013627479403574 	  Loss: 1.6894486854188622 	 Accuracy: 0.2275
Delta: 0.009554225812461641 	  Loss: 1.6776442434180197 	 Accuracy: 0.2225

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.008400603125010868 	  Loss: 1.6725630766525375 	 Accuracy: 0.22625
num repe : 9
Delta:       0.0156354 	 Loss:       2.1909716
Delta:       0.0206670 	 Loss:       2.1556383
Delta:       0.0176327 	 Loss:       2.1259861
Delta:       0.0153011 	 Loss:       2.1063293
Delta:       0.0136336 	 Loss:       2.0947771
Delta:       0.0134920 	 Loss:       2.0848721
Delta:       0.0121640 	 Loss:       2.0771261
Delta:       0.0110839 	 Loss:       2.0722470
Delta:       0.0094331 	 Loss:       2.0693896
Delta:       0.0073960 	 Loss:       2.0681016
Delta:       0.0054370 	 Loss:       2.0676296
Delta:       0.0039224 	 Loss:       2.0674446
Delta:       0.0028799 	 Loss:       2.0672064
Delta:       0.0024246 	 Loss:       2.0671464
Delta:       0.0021062 	 Loss:       2.0671286
Delta:       0.0009799 	 Loss:       2.0671061
Delta:       0.0000018 	 Loss:       2.0671048
Delta:       0.0000000 	 Loss:       2.0671048
converged at iter  17
Delta: 0.020486253526311355 	  Loss: 2.1687010126647106 	 Accuracy: 0.2475
Delta: 0.01795413242856706 	  Loss: 2.124753373520804 	 Accuracy: 0.24875
Delta: 0.01718620927665303 	  Loss: 2.0496800907075685 	 Accuracy: 0.31875
Delta: 0.016604079484845075 	  Loss: 1.9343800452094624 	 Accuracy: 0.40625
Delta: 0.015078304721540621 	  Loss: 1.830096836972747 	 Accuracy: 0.4525
Delta: 0.013343887555147302 	  Loss: 1.7633276705258816 	 Accuracy: 0.46
Delta: 0.012228986874846479 	  Loss: 1.7175571069083413 	 Accuracy: 0.45625
Delta: 0.010356319124956579 	  Loss: 1.6859777836410421 	 Accuracy: 0.46125
Delta: 0.00927161525323643 	  Loss: 1.6681652885812372 	 Accuracy: 0.44625
Delta: 0.008667755801909609 	  Loss: 1.6593598125917266 	 Accuracy: 0.455
num repe : 10
Delta:       0.0156362 	 Loss:       2.1970422
Delta:       0.0207747 	 Loss:       2.1633441
Delta:       0.0182434 	 Loss:       2.1278100
Delta:       0.0156902 	 Loss:       2.0982901
Delta:       0.0124515 	 Loss:       2.0826493
Delta:       0.0095203 	 Loss:       2.0792544
Delta:       0.0086948 	 Loss:       2.0779917
Delta:       0.0089578 	 Loss:       2.0765657
Delta:       0.0073277 	 Loss:       2.0754279
Delta:       0.0052941 	 Loss:       2.0748407
Delta:       0.0039222 	 Loss:       2.0745471
Delta:       0.0028141 	 Loss:       2.0744705
Delta:       0.0013869 	 Loss:       2.0744385
Delta:       0.0000012 	 Loss:       2.0744370
Delta:       0.0000000 	 Loss:       2.0744370
converged at iter  14
Delta: 0.020562348916489365 	  Loss: 2.1759028384486707 	 Accuracy: 0.23625
Delta: 0.01821630793983949 	  Loss: 2.1295165878670295 	 Accuracy: 0.34625
Delta: 0.016614662772624116 	  Loss: 2.0527758134152556 	 Accuracy: 0.40125
Delta: 0.01605969628364377 	  Loss: 1.9437496422654865 	 Accuracy: 0.3575
Delta: 0.014829090179002174 	  Loss: 1.8426525421966082 	 Accuracy: 0.34375
Delta: 0.013368444565202637 	  Loss: 1.769456642691063 	 Accuracy: 0.35375
Delta: 0.012132568125104437 	  Loss: 1.720731620660505 	 Accuracy: 0.31875
Delta: 0.010687065665242555 	  Loss: 1.6936371896053686 	 Accuracy: 0.30375
Delta: 0.009823165556499237 	  Loss: 1.6791175962803613 	 Accuracy: 0.3
Delta: 0.008840333625258903 	  Loss: 1.671182878445228 	 Accuracy: 0.3

,recoding,learning,prop_source,prop_target,pure_source_mean,pure_source_var,test_source_mean,test_source_var,pure_target_mean,pure_target_var,test_target_mean,test_target_var
0,coot,unsupervised,1,0,1.0,0.0,1.0,0.0,0.382625,0.029802,0.3785,0.028606
1,jdcoot,unsupervised,1,0,1.0,0.0,1.0,0.0,0.383875,0.015073,0.3970,0.016362

In [16]:
df_results

,repetition,recoding,learning,prop_source,prop_target,pure_source,test_source,pure_target,test_target
0,0,coot,unsupervised,1,0,1.0,1.0,0.20125,0.200
1,0,jdcoot,unsupervised,1,0,1.0,1.0,0.44000,0.480
2,1,coot,unsupervised,1,0,1.0,1.0,0.72875,0.695
3,1,jdcoot,unsupervised,1,0,1.0,1.0,0.38125,0.355
4,2,coot,unsupervised,1,0,1.0,1.0,0.30250,0.345
5,2,jdcoot,unsupervised,1,0,1.0,1.0,0.38125,0.365
6,3,coot,unsupervised,1,0,1.0,1.0,0.18625,0.175
7,3,jdcoot,unsupervised,1,0,1.0,1.0,0.54000,0.535
8,4,coot,unsupervised,1,0,1.0,1.0,0.54875,0.545
9,4,jdcoot,unsupervised,1,0,1.0,1.0,0.35500,0.400
10,5,coot,unsupervised,1,0,1.0,1.0,0.28500,0.235
11,5,jdcoot,unsupervised,1,0,1.0,1.0,0.19250,0.180
12,6,coot,unsupervised,1,0,1.0,1.0,0.53875,0.545
13,6,jdcoot,unsupervised,1,0,1.0,1.0,0.56750,0.600
14,7,coot,unsupervised,1,0,1.0,1.0,0.28875,0.315
15,7,jdcoot,unsupervised,1,0,1.0,1.0,0.22625,0.265
16,8,coot,unsupervised,1,0,1.0,1.0,0.37750,0.330
17,8,jdcoot,unsupervised,1,0,1.0,1.0,0.45500,0.475
18,9,coot,unsupervised,1,0,1.0,1.0,0.36875,0.400
19,9,jdcoot,unsupervised,1,0,1.0,1.0,0.30000,0.315