# Test on CaffeNet4096 and GoogleNet1024 Data

In [12]:
import sklearn
import scipy 
import numpy as np
import pandas as pd
import os
import sys

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "0"
sys.path.append(os.path.abspath("src"))
import jdcoot
from scipy.io import loadmat
featuresToUse = ["CaffeNet4096", "GoogleNet1024"] 
sourceDomainName = ['amazon'] #['caltech10','amazon','webcam']
targetDomainName = ['amazon'] #['caltech10','amazon','webcam']

tests = []
data_source = {}
data_target = {}

min_max_scaler = sklearn.preprocessing.MinMaxScaler()
# Collab
possible_data = loadmat(os.path.join("data/", "features", featuresToUse[0],
                                                 "caltech10" + '.mat'))
feat = possible_data['fts'].astype(float)
labels = possible_data['labels'].ravel()
S_data = [feat, labels]
S_nClass = len(np.unique(labels)) # nb de class in source data
possible_data = loadmat(os.path.join("data/", "features", featuresToUse[1],
                                                 "amazon" + '.mat'))
feat = possible_data['fts'].astype(float)
labels = possible_data['labels'].ravel()
T_data = [feat, labels]
T_nClass = len(np.unique(labels)) # nb de class in target data

source=pd.DataFrame(np.concatenate((S_data[0],S_data[1].reshape(-1,1)),axis=1),columns=['X'+str(i) for i in range(S_data[0].shape[1])]+['Z'])
target=pd.DataFrame(np.concatenate((T_data[0],T_data[1].reshape(-1,1)),axis=1),columns=['X'+str(i) for i in range(T_data[0].shape[1])]+['Z'])

source.loc[:,'Z'] = source.loc[:, 'Z'] - 1
target.loc[:,'Z'] = target.loc[:, 'Z'] - 1

In [6]:
from jdcoot.models.discrete_unsupervised_jdcoot import discrete_unsupervised_jdcoot
from jdcoot.models.discrete_semisupervised_jdcoot import discrete_semisupervised_jdcoot
from jdcoot.models.discrete_partial_jdcoot import discrete_partial_jdcoot
from jdcoot.models.discrete_unsupervised_coot import discrete_unsupervised_coot
from jdcoot.models.discrete_semisupervised_coot import discrete_semisupervised_coot
from jdcoot.models.discrete_partial_coot import discrete_partial_coot
from jdcoot.models.discrete_semisupervised_reference import discrete_semisupervised_reference
from jdcoot.models.discrete_partial_reference import discrete_partial_reference

In [13]:
results = []
numRepetitions = 10
nbtrain = 800
nbtest = 200
a = 0.4

prop_target_values_s = [0.01, 0.05, 0.1, 0.2, 0.4]
prop_target_values_p = [0.01, 0.05, 0.1, 0.2, 0.4]

XtotS = np.array(S_data[0], dtype=float)
YtotS = np.array(S_data[1], dtype=int).reshape(-1, 1) - 1

XtotT = np.array(T_data[0], dtype=float)
YtotT = np.array(T_data[1], dtype=int).reshape(-1, 1) - 1

for repe in range(numRepetitions):
    print("num repe :", repe + 1)

    a = np.random.choice(np.arange(len(source)), math.ceil(0.7 * len(source)), replace=False)
    b = np.random.choice(np.arange(len(target)), math.ceil(0.7 * len(target)), replace=False)

    S_test = source.iloc[np.setdiff1d(np.arange(len(source)), a), :].reset_index(drop=True)
    T_test = target.iloc[np.setdiff1d(np.arange(len(target)), b), :].reset_index(drop=True)
    S = source.iloc[a, :].reset_index(drop=True)
    T = target.iloc[b, :].reset_index(drop=True)

    # =========================================================
    # UNSUPERVISED
    # =========================================================
     # COOT
    pure_source, pure_target, test_source, test_target = \
        discrete_unsupervised_coot(S, T, S_test, T_test)

    results.append({
        "repetition": repe,
        "recoding": "coot",
        "learning": "unsupervised",
        "prop_source": 1,
        "prop_target": 0,
        "pure_source": pure_source,
        "test_source": test_source,
        "pure_target": pure_target,
        "test_target": test_target,
    })
    
    # JDCOOT
    pure_source, pure_target, test_source, test_target = \
        discrete_unsupervised_jdcoot(S, T, S_test, T_test)

    results.append({
        "repetition": repe,
        "recoding": "jdcoot",
        "learning": "unsupervised",
        "prop_source": 1,
        "prop_target": 0,
        "pure_source": pure_source,
        "test_source": test_source,
        "pure_target": pure_target,
        "test_target": test_target,
    })

   
import pandas as pd

df_results = pd.DataFrame(results)


df_results

df_summary = (
    df_results
    .groupby(
        ["recoding", "learning", "prop_source", "prop_target"],
        as_index=False
    )
    .agg(
        pure_source_mean=("pure_source", "mean"),
        pure_source_var=("pure_source", "var"),
        test_source_mean=("test_source", "mean"),
        test_source_var=("test_source", "var"),
        pure_target_mean=("pure_target", "mean"),
        pure_target_var=("pure_target", "var"),
        test_target_mean=("test_target", "mean"),
        test_target_var=("test_target", "var"),
    )
)

df_summary

num repe : 1
Delta:       0.0457897 	 Loss:       1.9857736
Delta:       0.0595184 	 Loss:       1.6529402
Delta:       0.0548598 	 Loss:       1.4643111
Delta:       0.0453964 	 Loss:       1.4155604
Delta:       0.0351196 	 Loss:       1.4021765
Delta:       0.0266262 	 Loss:       1.3962759
Delta:       0.0237078 	 Loss:       1.3928607
Delta:       0.0221364 	 Loss:       1.3903178
Delta:       0.0208595 	 Loss:       1.3881691
Delta:       0.0179384 	 Loss:       1.3871043
Delta:       0.0153784 	 Loss:       1.3863319
Delta:       0.0172630 	 Loss:       1.3853919
Delta:       0.0163311 	 Loss:       1.3846756
Delta:       0.0154443 	 Loss:       1.3841790
Delta:       0.0153176 	 Loss:       1.3837845
Delta:       0.0145081 	 Loss:       1.3834240
Delta:       0.0125875 	 Loss:       1.3831766
Delta:       0.0117419 	 Loss:       1.3829772
Delta:       0.0127322 	 Loss:       1.3826721
Delta:       0.0143546 	 Loss:       1.3822381
Delta:       0.0132382 	 Loss:       1.3819110
Delta:       0.0132539 	 Loss:       1.3816354
Delta:       0.0123467 	 Loss:       1.3814650
Delta:       0.0116175 	 Loss:       1.3813414
Delta:       0.0115792 	 Loss:       1.3812797
Delta:       0.0119889 	 Loss:       1.3811807
Delta:       0.0108146 	 Loss:       1.3810955
Delta:       0.0088192 	 Loss:       1.3810369
Delta:       0.0083609 	 Loss:       1.3810113
Delta:       0.0115591 	 Loss:       1.3809587
Delta:       0.0114272 	 Loss:       1.3808834
Delta:       0.0114966 	 Loss:       1.3807930
Delta:       0.0092833 	 Loss:       1.3807500
Delta:       0.0111574 	 Loss:       1.3806575
Delta:       0.0118902 	 Loss:       1.3805319
Delta:       0.0099159 	 Loss:       1.3804701
Delta:       0.0112355 	 Loss:       1.3804108
Delta:       0.0110804 	 Loss:       1.3803735
Delta:       0.0081271 	 Loss:       1.3803572
Delta:       0.0071840 	 Loss:       1.3803533
Delta:       0.0063617 	 Loss:       1.3803521
Delta:       0.0059175 	 Loss:       1.3803513
Delta:       0.0048323 	 Loss:       1.3803513
converged at iter  42
Delta: 0.05561708607740502 	  Loss: 1.8101476271541845 	 Accuracy: 0.15797317436661698
Delta: 0.04197301141425342 	  Loss: 1.7699068309411765 	 Accuracy: 0.15648286140089418
Delta: 0.033486208261776215 	  Loss: 1.7533041038163493 	 Accuracy: 0.15648286140089418
Delta: 0.028263902537622856 	  Loss: 1.7444423041410881 	 Accuracy: 0.15648286140089418
Delta: 0.0238176571667934 	  Loss: 1.740077337747378 	 Accuracy: 0.15648286140089418
Delta: 0.023400160694079398 	  Loss: 1.7365753640916788 	 Accuracy: 0.15648286140089418
Delta: 0.02126770348466735 	  Loss: 1.7328294974323633 	 Accuracy: 0.15648286140089418
Delta: 0.020766408310536125 	  Loss: 1.7310538156479796 	 Accuracy: 0.15648286140089418
Delta: 0.019702233202208166 	  Loss: 1.7284233801213724 	 Accuracy: 0.15648286140089418
Delta: 0.018419785682836802 	  Loss: 1.7270433474121194 	 Accuracy: 0.15648286140089418
num repe : 2
Delta:       0.0457950 	 Loss:       1.9887325
Delta:       0.0599621 	 Loss:       1.6614822
Delta:       0.0532063 	 Loss:       1.5330568
Delta:       0.0430252 	 Loss:       1.4950838
Delta:       0.0357380 	 Loss:       1.4786834
Delta:       0.0343451 	 Loss:       1.4603365
Delta:       0.0361024 	 Loss:       1.4330966
Delta:       0.0356152 	 Loss:       1.4104800
Delta:       0.0321753 	 Loss:       1.3981685
Delta:       0.0291326 	 Loss:       1.3882940
Delta:       0.0258193 	 Loss:       1.3831488
Delta:       0.0225929 	 Loss:       1.3802910
Delta:       0.0215440 	 Loss:       1.3782715
Delta:       0.0202454 	 Loss:       1.3766416
Delta:       0.0178110 	 Loss:       1.3756544
Delta:       0.0177926 	 Loss:       1.3746697
Delta:       0.0168488 	 Loss:       1.3739339
Delta:       0.0158286 	 Loss:       1.3733836
Delta:       0.0146678 	 Loss:       1.3729460
Delta:       0.0145121 	 Loss:       1.3726202
Delta:       0.0137082 	 Loss:       1.3723074
Delta:       0.0143253 	 Loss:       1.3718810
Delta:       0.0151116 	 Loss:       1.3714944
Delta:       0.0154263 	 Loss:       1.3711497
Delta:       0.0140281 	 Loss:       1.3709645
Delta:       0.0126501 	 Loss:       1.3707948
Delta:       0.0130890 	 Loss:       1.3706411
Delta:       0.0121535 	 Loss:       1.3705198
Delta:       0.0133277 	 Loss:       1.3704113
Delta:       0.0125884 	 Loss:       1.3703013
Delta:       0.0128759 	 Loss:       1.3701597
Delta:       0.0114632 	 Loss:       1.3700470
Delta:       0.0124348 	 Loss:       1.3699287
Delta:       0.0120039 	 Loss:       1.3698359
Delta:       0.0119300 	 Loss:       1.3697213
Delta:       0.0121626 	 Loss:       1.3696436
Delta:       0.0108979 	 Loss:       1.3695786
Delta:       0.0117742 	 Loss:       1.3695001
Delta:       0.0122348 	 Loss:       1.3693875
Delta:       0.0099724 	 Loss:       1.3693597
Delta:       0.0096926 	 Loss:       1.3693326
Delta:       0.0102365 	 Loss:       1.3692667
Delta:       0.0096523 	 Loss:       1.3692404
Delta:       0.0094141 	 Loss:       1.3692195
Delta:       0.0123684 	 Loss:       1.3691731
Delta:       0.0096164 	 Loss:       1.3691600
Delta:       0.0079158 	 Loss:       1.3691405
Delta:       0.0094505 	 Loss:       1.3691281
Delta:       0.0082006 	 Loss:       1.3691180
Delta:       0.0098058 	 Loss:       1.3691151
Delta:       0.0077057 	 Loss:       1.3691050
Delta:       0.0106006 	 Loss:       1.3690858
Delta:       0.0111037 	 Loss:       1.3690734
Delta:       0.0082167 	 Loss:       1.3690563
Delta:       0.0088549 	 Loss:       1.3690461
Delta:       0.0090765 	 Loss:       1.3690385
Delta:       0.0089989 	 Loss:       1.3690362
Delta:       0.0077581 	 Loss:       1.3690271
Delta:       0.0091350 	 Loss:       1.3690193
Delta:       0.0063026 	 Loss:       1.3690181
Delta:       0.0089242 	 Loss:       1.3690174
Delta:       0.0086998 	 Loss:       1.3690049
Delta:       0.0103308 	 Loss:       1.3689872
Delta:       0.0082837 	 Loss:       1.3689726
Delta:       0.0092384 	 Loss:       1.3689693
Delta:       0.0078082 	 Loss:       1.3689672
Delta:       0.0069828 	 Loss:       1.3689666
Delta:       0.0072013 	 Loss:       1.3689666
converged at iter  67
Delta: 0.055807975215423015 	  Loss: 1.8319281336007283 	 Accuracy: 0.10432190760059612
Delta: 0.041322494916339575 	  Loss: 1.7934502307443116 	 Accuracy: 0.10432190760059612
Delta: 0.03203971286539338 	  Loss: 1.7830826357994756 	 Accuracy: 0.09836065573770492
Delta: 0.028777024177773385 	  Loss: 1.7730423937202735 	 Accuracy: 0.10134128166915052
Delta: 0.023238472350522767 	  Loss: 1.7700191086751893 	 Accuracy: 0.10134128166915052
Delta: 0.023853497597896067 	  Loss: 1.7675795023825023 	 Accuracy: 0.10283159463487332
Delta: 0.023538661966508556 	  Loss: 1.7631964721525564 	 Accuracy: 0.10134128166915052
Delta: 0.020902888102335853 	  Loss: 1.7606152682795746 	 Accuracy: 0.09985096870342772
Delta: 0.018909763312690217 	  Loss: 1.7587348081589869 	 Accuracy: 0.09985096870342772
Delta: 0.02020075257289923 	  Loss: 1.7578176828562313 	 Accuracy: 0.10134128166915052
num repe : 3
Delta:       0.0457995 	 Loss:       1.9731502
Delta:       0.0601304 	 Loss:       1.5692941
Delta:       0.0529785 	 Loss:       1.4318100
Delta:       0.0436421 	 Loss:       1.3951595
Delta:       0.0342356 	 Loss:       1.3808446
Delta:       0.0280735 	 Loss:       1.3732626
Delta:       0.0271580 	 Loss:       1.3673550
Delta:       0.0256843 	 Loss:       1.3631077
Delta:       0.0216173 	 Loss:       1.3605722
Delta:       0.0198792 	 Loss:       1.3590101
Delta:       0.0205199 	 Loss:       1.3568525
Delta:       0.0192165 	 Loss:       1.3549579
Delta:       0.0188767 	 Loss:       1.3531240
Delta:       0.0154633 	 Loss:       1.3524439
Delta:       0.0161631 	 Loss:       1.3517779
Delta:       0.0157040 	 Loss:       1.3511609
Delta:       0.0144107 	 Loss:       1.3508412
Delta:       0.0146367 	 Loss:       1.3504155
Delta:       0.0145442 	 Loss:       1.3501147
Delta:       0.0137714 	 Loss:       1.3498320
Delta:       0.0145759 	 Loss:       1.3496048
Delta:       0.0130757 	 Loss:       1.3494048
Delta:       0.0120717 	 Loss:       1.3491933
Delta:       0.0123192 	 Loss:       1.3490397
Delta:       0.0111554 	 Loss:       1.3489621
Delta:       0.0103641 	 Loss:       1.3489267
Delta:       0.0099378 	 Loss:       1.3488766
Delta:       0.0112012 	 Loss:       1.3487156
Delta:       0.0111447 	 Loss:       1.3484689
Delta:       0.0099366 	 Loss:       1.3483729
Delta:       0.0099421 	 Loss:       1.3483410
Delta:       0.0103010 	 Loss:       1.3482902
Delta:       0.0111506 	 Loss:       1.3482197
Delta:       0.0107907 	 Loss:       1.3481557
Delta:       0.0111068 	 Loss:       1.3480145
Delta:       0.0107222 	 Loss:       1.3479359
Delta:       0.0110950 	 Loss:       1.3478303
Delta:       0.0111035 	 Loss:       1.3477215
Delta:       0.0105635 	 Loss:       1.3476339
Delta:       0.0115640 	 Loss:       1.3475416
Delta:       0.0109258 	 Loss:       1.3474289
Delta:       0.0125774 	 Loss:       1.3472973
Delta:       0.0119969 	 Loss:       1.3471337
Delta:       0.0094137 	 Loss:       1.3470537
Delta:       0.0089661 	 Loss:       1.3470321
Delta:       0.0091691 	 Loss:       1.3470060
Delta:       0.0065308 	 Loss:       1.3470013
Delta:       0.0071327 	 Loss:       1.3470012
converged at iter  47
Delta: 0.05570965599188099 	  Loss: 1.793523429418113 	 Accuracy: 0.14008941877794337
Delta: 0.042753243733749384 	  Loss: 1.7565175642861603 	 Accuracy: 0.13859910581222057
Delta: 0.03414380178286692 	  Loss: 1.7414969974839982 	 Accuracy: 0.13859910581222057
Delta: 0.02895553585625767 	  Loss: 1.7329577798790528 	 Accuracy: 0.13859910581222057
Delta: 0.024288668184108762 	  Loss: 1.7280973297951094 	 Accuracy: 0.13710879284649777
Delta: 0.019884858432183378 	  Loss: 1.7253522991028174 	 Accuracy: 0.13114754098360656
Delta: 0.020231252241905116 	  Loss: 1.7232040367944865 	 Accuracy: 0.13710879284649777
Delta: 0.020546909282478914 	  Loss: 1.7209063886374794 	 Accuracy: 0.13561847988077497
Delta: 0.02015496664577185 	  Loss: 1.7192777817441733 	 Accuracy: 0.13561847988077497
Delta: 0.020495708924232067 	  Loss: 1.7168399564444041 	 Accuracy: 0.13710879284649777
num repe : 4
Delta:       0.0457949 	 Loss:       1.9872325
Delta:       0.0602084 	 Loss:       1.6418833
Delta:       0.0528515 	 Loss:       1.5167105
Delta:       0.0451192 	 Loss:       1.4735577
Delta:       0.0384861 	 Loss:       1.4482880
Delta:       0.0351558 	 Loss:       1.4309795
Delta:       0.0319699 	 Loss:       1.4196746
Delta:       0.0285383 	 Loss:       1.4138125
Delta:       0.0242323 	 Loss:       1.4104022
Delta:       0.0229258 	 Loss:       1.4078320
Delta:       0.0180096 	 Loss:       1.4066176
Delta:       0.0168683 	 Loss:       1.4059038
Delta:       0.0154556 	 Loss:       1.4054436
Delta:       0.0155285 	 Loss:       1.4050479
Delta:       0.0154111 	 Loss:       1.4045535
Delta:       0.0154527 	 Loss:       1.4039210
Delta:       0.0141496 	 Loss:       1.4035945
Delta:       0.0143796 	 Loss:       1.4032348
Delta:       0.0157703 	 Loss:       1.4028935
Delta:       0.0131982 	 Loss:       1.4026026
Delta:       0.0134368 	 Loss:       1.4024047
Delta:       0.0126871 	 Loss:       1.4021727
Delta:       0.0147970 	 Loss:       1.4019385
Delta:       0.0134619 	 Loss:       1.4016627
Delta:       0.0133382 	 Loss:       1.4015086
Delta:       0.0121610 	 Loss:       1.4014312
Delta:       0.0125191 	 Loss:       1.4013368
Delta:       0.0129765 	 Loss:       1.4012604
Delta:       0.0128622 	 Loss:       1.4011519
Delta:       0.0115004 	 Loss:       1.4010877
Delta:       0.0109497 	 Loss:       1.4010133
Delta:       0.0134271 	 Loss:       1.4008351
Delta:       0.0142670 	 Loss:       1.4006011
Delta:       0.0137256 	 Loss:       1.4003803
Delta:       0.0133571 	 Loss:       1.4002120
Delta:       0.0137063 	 Loss:       1.3998153
Delta:       0.0134495 	 Loss:       1.3995386
Delta:       0.0139774 	 Loss:       1.3993420
Delta:       0.0125270 	 Loss:       1.3991192
Delta:       0.0139217 	 Loss:       1.3987133
Delta:       0.0151995 	 Loss:       1.3980292
Delta:       0.0149146 	 Loss:       1.3973389
Delta:       0.0158569 	 Loss:       1.3968332
Delta:       0.0136629 	 Loss:       1.3964058
Delta:       0.0138553 	 Loss:       1.3960860
Delta:       0.0142658 	 Loss:       1.3957404
Delta:       0.0140805 	 Loss:       1.3954562
Delta:       0.0133240 	 Loss:       1.3952228
Delta:       0.0138325 	 Loss:       1.3949243
Delta:       0.0137585 	 Loss:       1.3946065
Delta:       0.0144544 	 Loss:       1.3942994
Delta:       0.0147231 	 Loss:       1.3939872
Delta:       0.0142517 	 Loss:       1.3937504
Delta:       0.0136204 	 Loss:       1.3934765
Delta:       0.0139615 	 Loss:       1.3932685
Delta:       0.0116238 	 Loss:       1.3931664
Delta:       0.0115062 	 Loss:       1.3930756
Delta:       0.0109626 	 Loss:       1.3930095
Delta:       0.0123446 	 Loss:       1.3928523
Delta:       0.0120844 	 Loss:       1.3927606
Delta:       0.0109335 	 Loss:       1.3926917
Delta:       0.0125451 	 Loss:       1.3925433
Delta:       0.0123921 	 Loss:       1.3923286
Delta:       0.0142776 	 Loss:       1.3920119
Delta:       0.0129345 	 Loss:       1.3918191
Delta:       0.0137893 	 Loss:       1.3916593
Delta:       0.0130143 	 Loss:       1.3914920
Delta:       0.0147852 	 Loss:       1.3911249
Delta:       0.0135339 	 Loss:       1.3908649
Delta:       0.0143095 	 Loss:       1.3906604
Delta:       0.0134701 	 Loss:       1.3904696
Delta:       0.0137622 	 Loss:       1.3903230
Delta:       0.0122846 	 Loss:       1.3901837
Delta:       0.0131333 	 Loss:       1.3900682
Delta:       0.0102291 	 Loss:       1.3900159
Delta:       0.0100928 	 Loss:       1.3899891
Delta:       0.0114589 	 Loss:       1.3899205
Delta:       0.0109961 	 Loss:       1.3898484
Delta:       0.0097541 	 Loss:       1.3898305
Delta:       0.0091464 	 Loss:       1.3898216
Delta:       0.0100958 	 Loss:       1.3897955
Delta:       0.0094263 	 Loss:       1.3897659
Delta:       0.0090982 	 Loss:       1.3897418
Delta:       0.0103693 	 Loss:       1.3897152
Delta:       0.0095620 	 Loss:       1.3896950
Delta:       0.0089585 	 Loss:       1.3896848
Delta:       0.0079140 	 Loss:       1.3896827
Delta:       0.0060904 	 Loss:       1.3896826
Delta:       0.0000000 	 Loss:       1.3896826
converged at iter  88
Delta: 0.05561282684654022 	  Loss: 1.8190174621041688 	 Accuracy: 0.16095380029806258
Delta: 0.041805557212246686 	  Loss: 1.7825688665672565 	 Accuracy: 0.16244411326378538
Delta: 0.03360937547858726 	  Loss: 1.7671661167423163 	 Accuracy: 0.15946348733233978
Delta: 0.027488823107300497 	  Loss: 1.7590932333102391 	 Accuracy: 0.16095380029806258
Delta: 0.02503453245649897 	  Loss: 1.7535114941044598 	 Accuracy: 0.16244411326378538
Delta: 0.02414599352378439 	  Loss: 1.7500478987365637 	 Accuracy: 0.17585692995529062
Delta: 0.022221028019694607 	  Loss: 1.7468647655042322 	 Accuracy: 0.16244411326378538
Delta: 0.023526230710427632 	  Loss: 1.7443492713223192 	 Accuracy: 0.15946348733233978
Delta: 0.02102352324966465 	  Loss: 1.742624824395877 	 Accuracy: 0.16393442622950818
Delta: 0.01980723195236372 	  Loss: 1.74111439021355 	 Accuracy: 0.16393442622950818
num repe : 5
Delta:       0.0457770 	 Loss:       1.9611384
Delta:       0.0596903 	 Loss:       1.5559578
Delta:       0.0533941 	 Loss:       1.4329761
Delta:       0.0441597 	 Loss:       1.3823764
Delta:       0.0350675 	 Loss:       1.3675416
Delta:       0.0302946 	 Loss:       1.3569669
Delta:       0.0262664 	 Loss:       1.3509980
Delta:       0.0248736 	 Loss:       1.3464647
Delta:       0.0217489 	 Loss:       1.3435276
Delta:       0.0208191 	 Loss:       1.3413170
Delta:       0.0188583 	 Loss:       1.3394601
Delta:       0.0185890 	 Loss:       1.3382126
Delta:       0.0170495 	 Loss:       1.3372357
Delta:       0.0173059 	 Loss:       1.3363597
Delta:       0.0161080 	 Loss:       1.3357283
Delta:       0.0154745 	 Loss:       1.3351783
Delta:       0.0157774 	 Loss:       1.3347355
Delta:       0.0133858 	 Loss:       1.3345089
Delta:       0.0137024 	 Loss:       1.3342422
Delta:       0.0124352 	 Loss:       1.3340189
Delta:       0.0131314 	 Loss:       1.3337925
Delta:       0.0126266 	 Loss:       1.3336389
Delta:       0.0130313 	 Loss:       1.3334253
Delta:       0.0125888 	 Loss:       1.3332558
Delta:       0.0129639 	 Loss:       1.3329712
Delta:       0.0117521 	 Loss:       1.3327754
Delta:       0.0115145 	 Loss:       1.3326425
Delta:       0.0119191 	 Loss:       1.3324568
Delta:       0.0120488 	 Loss:       1.3323662
Delta:       0.0109464 	 Loss:       1.3322396
Delta:       0.0100422 	 Loss:       1.3321782
Delta:       0.0102322 	 Loss:       1.3321228
Delta:       0.0088071 	 Loss:       1.3320991
Delta:       0.0102429 	 Loss:       1.3320265
Delta:       0.0112209 	 Loss:       1.3319591
Delta:       0.0107350 	 Loss:       1.3319215
Delta:       0.0086066 	 Loss:       1.3318916
Delta:       0.0107297 	 Loss:       1.3318218
Delta:       0.0120503 	 Loss:       1.3317211
Delta:       0.0105494 	 Loss:       1.3316513
Delta:       0.0106086 	 Loss:       1.3315799
Delta:       0.0084804 	 Loss:       1.3315520
Delta:       0.0083782 	 Loss:       1.3315395
Delta:       0.0085943 	 Loss:       1.3315033
Delta:       0.0072234 	 Loss:       1.3314982
Delta:       0.0070735 	 Loss:       1.3314968
Delta:       0.0067048 	 Loss:       1.3314942
Delta:       0.0038817 	 Loss:       1.3314942
converged at iter  47
Delta: 0.055018599710016616 	  Loss: 1.7864958590377507 	 Accuracy: 0.13561847988077497
Delta: 0.04181366388926972 	  Loss: 1.7443150160236613 	 Accuracy: 0.13859910581222057
Delta: 0.032129158309173456 	  Loss: 1.7295359969335644 	 Accuracy: 0.14008941877794337
Delta: 0.028329047211656695 	  Loss: 1.7223483713943841 	 Accuracy: 0.13859910581222057
Delta: 0.02097814323760154 	  Loss: 1.7191194855880383 	 Accuracy: 0.14008941877794337
Delta: 0.018700830158902716 	  Loss: 1.7170150710535625 	 Accuracy: 0.13859910581222057
Delta: 0.021236877528865904 	  Loss: 1.7149432707096248 	 Accuracy: 0.13412816691505217
Delta: 0.020190690262483324 	  Loss: 1.7125789350545386 	 Accuracy: 0.13859910581222057
Delta: 0.019109223066165547 	  Loss: 1.711228018452237 	 Accuracy: 0.14008941877794337
Delta: 0.020369842151452565 	  Loss: 1.7091045317660107 	 Accuracy: 0.14008941877794337
num repe : 6
Delta:       0.0457925 	 Loss:       1.9715095
Delta:       0.0604474 	 Loss:       1.5346923
Delta:       0.0543529 	 Loss:       1.3912276
Delta:       0.0422183 	 Loss:       1.3638677
Delta:       0.0312241 	 Loss:       1.3544577
Delta:       0.0270480 	 Loss:       1.3493298
Delta:       0.0243412 	 Loss:       1.3459133
Delta:       0.0227335 	 Loss:       1.3433033
Delta:       0.0223917 	 Loss:       1.3408235
Delta:       0.0193139 	 Loss:       1.3389812
Delta:       0.0165282 	 Loss:       1.3382138
Delta:       0.0163017 	 Loss:       1.3377807
Delta:       0.0162336 	 Loss:       1.3372320
Delta:       0.0153378 	 Loss:       1.3367961
Delta:       0.0164983 	 Loss:       1.3360125
Delta:       0.0174085 	 Loss:       1.3351877
Delta:       0.0171293 	 Loss:       1.3344114
Delta:       0.0161708 	 Loss:       1.3338020
Delta:       0.0165121 	 Loss:       1.3332205
Delta:       0.0155022 	 Loss:       1.3328495
Delta:       0.0133418 	 Loss:       1.3325424
Delta:       0.0123295 	 Loss:       1.3323810
Delta:       0.0124304 	 Loss:       1.3322362
Delta:       0.0135930 	 Loss:       1.3319492
Delta:       0.0140274 	 Loss:       1.3316786
Delta:       0.0125666 	 Loss:       1.3315641
Delta:       0.0103659 	 Loss:       1.3314989
Delta:       0.0101155 	 Loss:       1.3314722
Delta:       0.0095345 	 Loss:       1.3314392
Delta:       0.0103125 	 Loss:       1.3314021
Delta:       0.0105219 	 Loss:       1.3313439
Delta:       0.0110570 	 Loss:       1.3312766

,recoding,learning,prop_source,prop_target,pure_source_mean,pure_source_var,test_source_mean,test_source_var,pure_target_mean,pure_target_var,test_target_mean,test_target_var
0,coot,unsupervised,1,0,1.0,0.0,1.0,0.0,0.247094,0.017914,0.235192,0.021298
1,jdcoot,unsupervised,1,0,1.0,0.0,1.0,0.0,0.134426,0.000387,0.156794,0.001246

In [6]:
source

,X0,X1,X2,X3,X4,X5,X6,X7,X8,X9,...,X4087,X4088,X4089,X4090,X4091,X4092,X4093,X4094,X4095,Z
0,0.000000,2.505615,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,2.626899,...,0.000000,1.040452,0.000000,0.244105,0.538311,0.0,0.276814,0.000000,3.052249,0.0
1,0.000000,0.541579,0.313014,0.439709,0.000000,0.0,0.000000,0.000000,0.066556,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0
2,0.790015,1.988702,0.000000,0.564894,0.799181,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,2.120850,0.154717,0.0,0.469833,0.000000,5.262370,0.0
3,0.617630,0.000000,0.000000,0.531292,0.000000,0.0,0.000000,0.063488,0.000000,2.252140,...,0.000000,2.184550,0.000000,4.910501,0.125535,0.0,0.112745,0.000000,0.000000,0.0
4,0.086308,0.000000,0.000000,0.000000,0.078548,0.0,0.000000,0.000010,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.817102,1.381422,0.0,0.000000,0.000000,0.951175,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1118,0.000000,0.022826,0.000000,0.000000,2.617168,0.0,0.000000,0.000000,0.459277,0.053653,...,0.137178,0.000000,0.000000,6.440595,0.000000,0.0,1.054335,0.000000,3.067745,9.0
1119,0.000000,0.000000,0.074741,0.000000,4.969587,0.0,0.000000,0.000000,0.036196,0.000000,...,0.255194,0.000000,1.990188,0.282888,1.212520,0.0,1.090388,0.448483,0.914598,9.0
1120,0.067069,0.115418,0.830895,0.242900,0.000000,0.0,1.496816,0.000000,0.000000,0.134041,...,0.209118,0.000000,3.301181,0.085582,1.132439,0.0,0.142505,5.160264,0.000000,9.0
1121,0.000000,0.004926,1.155382,0.000000,0.703217,0.0,0.000000,0.000000,0.000000,0.000000,...,0.128274,0.000000,1.349111,1.215771,0.055194,0.0,0.001579,4.097502,0.000000,9.0
1122,0.000000,0.865644,0.374785,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.182173,0.000000,0.000000,1.953716,0.164944,0.0,3.278337,0.545753,0.000000,9.0

In [54]:
##j'enregistre les données pour utiliser la fonction get_data
XtotS=S_data[0]
YtotS=S_data[1].reshape(-1,1)
dS=XtotS.shape[1]

XtotT=T_data[0]
YtotT=T_data[1].reshape(-1,1)
dS=XtotT.shape[1]

In [4]:
YtotS

array([[ 1],
       [ 1],
       [ 1],
       ...,
       [10],
       [10],
       [10]], shape=(1123, 1))

In [5]:
target

,X0,X1,X2,X3,X4,X5,X6,X7,X8,X9,...,X1015,X1016,X1017,X1018,X1019,X1020,X1021,X1022,X1023,Z
0,0.099118,0.027809,5.621949,1.360448,0.685656,0.002524,0.000000,0.222424,0.191003,0.000000,...,0.017318,6.049173,1.842010,3.035832,0.000000,0.000000,6.033271,4.444777,0.777563,0.0
1,0.347711,0.184287,0.748881,0.006219,0.925356,0.021182,0.120170,0.270272,0.511218,1.030571,...,2.210097,0.035351,1.422792,0.144325,0.022264,0.009212,0.867809,0.000000,0.000000,0.0
2,0.312158,0.130354,9.469339,1.738539,0.250605,0.536205,0.043808,0.001698,0.042926,0.177376,...,0.282821,3.069715,3.318993,1.846191,0.137990,0.002659,0.498049,2.357793,1.681124,0.0
3,1.520496,0.000000,2.717583,0.232378,0.380185,0.017633,0.000000,0.002723,0.000121,0.001088,...,1.243849,1.708731,1.281769,0.507668,0.000000,0.000000,0.000000,5.837334,0.576506,0.0
4,0.016194,0.004919,3.887881,0.263304,0.214002,0.005530,0.000000,0.381500,0.031129,0.254239,...,1.618137,3.108347,2.338883,4.205164,0.000000,0.000000,0.655401,0.516461,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1118,0.969091,0.000000,0.381402,1.017459,0.455186,0.036823,0.558800,0.000000,0.693394,1.862158,...,0.257680,0.000631,0.000000,4.676526,0.438856,0.000000,0.408622,0.000000,0.894359,9.0
1119,1.784889,0.000000,1.994400,0.001530,0.000000,0.000000,0.000000,0.000000,0.000000,0.085341,...,0.636262,0.000000,0.000000,0.085995,0.346864,0.000000,0.000000,0.042968,0.000000,9.0
1120,0.735216,0.022285,0.312883,0.071244,0.117068,0.104118,3.865505,0.000000,1.534048,0.003839,...,0.000755,0.000000,0.005801,3.084740,0.000241,1.087159,0.000000,0.111928,0.035476,9.0
1121,2.829518,0.000000,1.018245,0.000000,0.067400,0.000000,0.121775,0.000000,0.001408,0.783866,...,0.138958,0.000000,0.000000,0.435474,0.053507,0.000000,0.000000,0.000000,0.000000,9.0
1122,2.545212,0.000000,1.934991,0.249499,0.054430,0.000000,0.018816,0.000000,0.008023,1.365772,...,0.028839,0.000000,0.000000,1.472044,0.466857,0.000000,0.000000,0.317850,0.000000,9.0

In [40]:
import math

a = np.random.choice(np.arange(len(source)), math.ceil(0.7 * len(source)), replace=False)
b = np.random.choice(np.arange(len(target)), math.ceil(0.7 * len(target)), replace=False)

S = source.iloc[np.setdiff1d(np.arange(len(source)), a), :].reset_index(drop=True)
T = target.iloc[np.setdiff1d(np.arange(len(target)), b), :].reset_index(drop=True)
S.loc[:,'Z'] = S.loc[:, 'Z'] - 1
T.loc[:,'Z'] = T.loc[:, 'Z'] - 1
S

,X0,X1,X2,X3,X4,X5,X6,X7,X8,X9,...,X4087,X4088,X4089,X4090,X4091,X4092,X4093,X4094,X4095,Z
0,0.000000,0.541579,0.313014,0.439709,0.000000,0.000000,0.000000,0.000000,0.066556,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0
1,0.790015,1.988702,0.000000,0.564894,0.799181,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,2.120850,0.154717,0.0,0.469833,0.000000,5.262370,0.0
2,0.617630,0.000000,0.000000,0.531292,0.000000,0.000000,0.000000,0.063488,0.000000,2.252140,...,0.000000,2.184550,0.000000,4.910501,0.125535,0.0,0.112745,0.000000,0.000000,0.0
3,0.000000,1.463537,5.183853,0.025951,0.000000,0.000000,0.000000,0.000000,0.000000,1.488524,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.122256,0.004240,0.0
4,0.000000,0.170888,0.000000,0.000000,0.000000,0.000000,0.063521,0.000000,0.000000,0.454374,...,0.000000,1.429933,0.554840,0.541800,1.083738,0.0,0.000000,0.000000,3.284321,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,0.000000,0.099487,0.000000,0.358152,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.979591,0.615633,0.0,3.503209,3.392829,0.000000,9.0
332,0.000000,0.000000,1.070332,0.000000,0.075848,0.000000,0.000000,0.000000,4.890769,0.000000,...,0.086535,0.000000,0.000000,5.318273,1.588444,0.0,3.033021,0.421139,2.786675,9.0
333,0.162715,0.026648,1.700754,2.961777,2.158117,0.177779,0.055664,0.000000,0.918156,1.964597,...,2.096488,0.000000,2.597763,0.000000,0.000000,0.0,0.000000,7.352889,0.000000,9.0
334,0.000000,0.000000,1.976933,0.331685,1.350030,0.000000,0.000000,0.000000,1.066061,0.000000,...,0.000000,0.000000,1.976173,0.159130,0.404491,0.0,0.260178,3.789771,0.000000,9.0
335,0.000000,0.022826,0.000000,0.000000,2.617168,0.000000,0.000000,0.000000,0.459277,0.053653,...,0.137178,0.000000,0.000000,6.440595,0.000000,0.0,1.054335,0.000000,3.067745,9.0

In [6]:
S_test = source.iloc[a, :].reset_index(drop=True)
T_test = target.iloc[b, :].reset_index(drop=True)

## Performance function

In [21]:
from jdcoot.models.discrete_unsupervised_jdcoot import discrete_unsupervised_jdcoot
discrete_unsupervised_jdcoot( S, T, S_test, T_test)

Delta: 0.021263271369738355 	  Loss: 2.162925540821128 	 Accuracy: 0.23333333333333334
Delta: 0.020000443417459525 	  Loss: 2.077011289336405 	 Accuracy: 0.31333333333333335
Delta: 0.019055079567157088 	  Loss: 1.9422504985775286 	 Accuracy: 0.25
Delta: 0.01773476045373289 	  Loss: 1.802982249875017 	 Accuracy: 0.21
Delta: 0.015708656033495066 	  Loss: 1.7122225735868104 	 Accuracy: 0.24
Delta: 0.01304045635073084 	  Loss: 1.668447388605732 	 Accuracy: 0.25666666666666665
Delta: 0.011122203384496373 	  Loss: 1.6476508289899934 	 Accuracy: 0.26

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.009831922530629051 	  Loss: 1.6385706561676203 	 Accuracy: 0.27
Delta: 0.008779914015812471 	  Loss: 1.6345855889900567 	 Accuracy: 0.27666666666666667
Delta: 0.008487088776980843 	  Loss: 1.6318112117679633 	 Accuracy: 0.28

(1.0, np.float64(0.28), 1.0, np.float64(0.29))

In [22]:
from jdcoot.models.discrete_semisupervised_jdcoot import discrete_semisupervised_jdcoot
discrete_semisupervised_jdcoot( S, T, S_test, T_test, prop_source=0.2)

Delta: 0.024053524611996183 	 Loss: 1.6337119828289188 	 Accuracy: 0.7925925925925926
Delta: 0.018851986726779076 	 Loss: 1.5343537041160054 	 Accuracy: 0.8333333333333334

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.011137290831537711 	 Loss: 1.512377304401441 	 Accuracy: 0.8814814814814815
Delta: 0.008898383276182921 	 Loss: 1.5038220107080624 	 Accuracy: 0.8888888888888888
Delta: 0.00752849928720386 	 Loss: 1.4995465365787748 	 Accuracy: 0.8888888888888888
Delta: 0.006613635026971421 	 Loss: 1.497288857462081 	 Accuracy: 0.8925925925925926
Delta: 0.006611524726305552 	 Loss: 1.4955469513757307 	 Accuracy: 0.8962962962962963
Delta: 0.0073783125194536985 	 Loss: 1.4934260133941064 	 Accuracy: 0.8962962962962963
Delta: 0.0056836282059234055 	 Loss: 1.4927349335644085 	 Accuracy: 0.8925925925925926
Delta: 0.004241687632779049 	 Loss: 1.4919720199010182 	 Accuracy: 0.9037037037037037

(1.0, np.float64(0.9037037037037037), 1.0, np.float64(0.95))

In [23]:
from jdcoot.models.discrete_partial_jdcoot import discrete_partial_jdcoot
discrete_partial_jdcoot( S, T, S_test, T_test, prop_source=0.2, prop_target=0.2)

Delta: 0.025503346276540908 	  Loss: 1.5519063252155973 	 Accuracy: 0.8458333333333333
Delta: 0.019436473734944684 	  Loss: 1.5308519522368509 	 Accuracy: 0.8333333333333334
Delta: 0.01559955183990858 	  Loss: 1.553659682250378 	 Accuracy: 0.7333333333333333

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.012302633000622535 	  Loss: 1.5842327411555606 	 Accuracy: 0.6833333333333333
Delta: 0.011518121632367699 	  Loss: 1.6134749115504106 	 Accuracy: 0.6458333333333334
Delta: 0.010455461558006807 	  Loss: 1.6352861741176763 	 Accuracy: 0.6125
Delta: 0.007988561068197716 	  Loss: 1.6525283440803118 	 Accuracy: 0.5458333333333333
Delta: 0.0062719520370890566 	  Loss: 1.6629730226830874 	 Accuracy: 0.475
Delta: 0.0047306425033502185 	  Loss: 1.6682945724370266 	 Accuracy: 0.44583333333333336
Delta: 0.0044830446044753156 	  Loss: 1.6714345977308909 	 Accuracy: 0.3541666666666667

(np.float64(0.3125),
 np.float64(0.3541666666666667),
 np.float64(0.6),
 np.float64(0.72))

In [24]:
from jdcoot.models.discrete_unsupervised_coot import discrete_unsupervised_coot
discrete_unsupervised_coot( S, T, S_test, T_test)

Delta:       0.0156694 	 Loss:       2.2046072
Delta:       0.0211672 	 Loss:       2.1673489
Delta:       0.0188271 	 Loss:       2.1294881

KeyboardInterrupt:

In [16]:
# get test set : save examples (nbtest per class) 
# take the last ones so that it's always the same set and we can compare results
# get train set with random
import numpy as np
from random import shuffle
from sklearn.preprocessing import OneHotEncoder as onehot
from sklearn.model_selection import train_test_split

def get_data(x, y, nbtrain, nbtest, nseed):
 
    y = y.ravel()
    n = x.shape[0]

    if nbtrain + nbtest > n:
        raise ValueError("nbtrain + nbtest exceeds total number of samples")

    np.random.seed(nseed)
    idx = np.random.permutation(n)

    train_idx = idx[:nbtrain]
    test_idx = idx[nbtrain:nbtrain + nbtest]

    xtrain = x[train_idx]
    ytrain = y[train_idx]

    xtest = x[test_idx]
    ytest = y[test_idx]

    return xtrain, ytrain, xtest, ytest


def get_data_2(x,y,nbtrain,nbtest,nseed):
    
    xtrain=np.zeros((0,x.shape[1]))
    ytrain=np.zeros((0))
    xtest=np.zeros((0,x.shape[1]))
    ytest=np.zeros((0))
    print(np.unique(y))
    for i in np.unique(y):
        xi=x[y.ravel()==i,:] # tous les exemples de la classe i

        if len(np.argwhere(y==i)) >= nbtrain+nbtest :
            ni = xi.shape[0] - nbtest    # nb d'exemples de la classe i pouvant servir lors de l'apprentissage
            np.random.seed(nseed)
            idx=np.random.permutation(ni)
          #print(idx[:nbtrain])
        
            xtrain=np.concatenate((xtrain,xi[idx[:nbtrain],:]),0)
            ytrain=np.concatenate((ytrain,i*np.ones(nbtrain)))

            xtest=np.concatenate((xtest,xi[ni:]),0)
            ytest=np.concatenate((ytest,i*np.ones(nbtest)))
 
        else:
            np.random.seed(nseed)
            idx=np.random.permutation(xi.shape[0])
        
            xtrain=np.concatenate((xtrain,xi[idx[:nbtrain]]),0)
            ytrain=np.concatenate((ytrain,i*np.ones(nbtrain)))
 
            xtest=np.concatenate((xtest,xi[idx[nbtrain:]]),0)
            ytest=np.concatenate((ytest,i*np.ones(xi.shape[0]-nbtrain)))
        
    return xtrain,ytrain,xtest,ytest


# semi-supervison
# get nsamples labelled examples for each class and one-hot-encode those labels
# nclass = number of classes in the dataset
# nsamples : number of labelles samples per class
# noLabClass : classes chosen to remain unlabelled
def get_labels(y,nsamples,nclass=10,noLabClass=[]):
    Y = np.zeros((len(y),nclass))
    for c in np.unique(y):
        if c not in noLabClass :
            idx = np.where(y==c)[0]
            Y[idx[:nsamples],int(c)]=1
    return Y

def generateSubset(X, Y, nPerClass):
    idx = []
    for c in np.unique(Y):
        idxClass = np.argwhere(Y == c).ravel()
        shuffle(idxClass)
        idx.extend(idxClass[0:min(nPerClass, len(idxClass))])
    return (X[idx, :], Y[idx])

In [9]:
from jdcoot.models.discrete_unsupervised_jdcoot import discrete_unsupervised_jdcoot
from jdcoot.models.discrete_semisupervised_jdcoot import discrete_semisupervised_jdcoot
from jdcoot.models.discrete_partial_jdcoot import discrete_partial_jdcoot
from jdcoot.models.discrete_unsupervised_coot import discrete_unsupervised_coot
from jdcoot.models.discrete_semisupervised_coot import discrete_semisupervised_coot
from jdcoot.models.discrete_partial_coot import discrete_partial_coot
from jdcoot.models.discrete_semisupervised_reference import discrete_semisupervised_reference
from jdcoot.models.discrete_partial_reference import discrete_partial_reference
from jdcoot.models.continuous_unsupervised_jdcoot import continuous_unsupervised_jdcoot
from jdcoot.models.continuous_unsupervised_coot import continuous_unsupervised_coot

## alpha

In [52]:
from jdcoot.utils import xcolumns, discrete_classifier, discrete_accuracy
from jdcoot.coot import init_matrix_np
from jdcoot.losses import loss_crossentropy2
from tf_keras.utils import to_categorical


def one_hot(y, nClass):
    return to_categorical(y, num_classes=nClass)


def one_cold(z_encoded):
    return np.argmax(z_encoded, axis=1)

source=pd.DataFrame(np.concatenate((S_data[0],S_data[1].reshape(-1,1)),axis=1),columns=['X'+str(i) for i in range(S_data[0].shape[1])]+['Z'])
target=pd.DataFrame(np.concatenate((T_data[0],T_data[1].reshape(-1,1)),axis=1),columns=['X'+str(i) for i in range(T_data[0].shape[1])]+['Z'])

source.loc[:,'Z'] = source.loc[:, 'Z'] - 1
target.loc[:,'Z'] = target.loc[:, 'Z'] - 1

classes = np.union1d(np.unique(source.Z), np.unique(target.Z))
nClass = len(classes)

x_source = source.loc[:, xcolumns(source)].values
z_source = source.Z.values

x_target = target.loc[:, xcolumns(target)].values
z_target = target.Z.values

z_target_u= np.unique(z_target)


max_diff2 = max(
    (x_source.max() - x_target.min())**2,
    (x_source.min() - x_target.max())**2
)
max_diff2
# Calcul de toutes les distances euclidiennes

# Distance maximale
#max_distance = np.max(dist_matrix^2)
#print("Max distance:", max_distance)

z1 = np.arange(10)
z2 = np.arange(10)
n_class = 10
Z1 = one_hot(z1, n_class)  # (10, 10)
Z2 = one_hot(z2, n_class)
fcost = np.max(loss_crossentropy2(Z1, Z2))

alpha = fcost/max_diff2
alpha

np.float64(0.044981382834838365)

In [ ]:
discrete_unsupervised_jdcoot( S, T, S_test, T_test,alpha=a)

## Data labellisation impact

In [53]:
import numpy as np
nbtrain=80
nbtest=20
XtotS = np.array(S_data[0], dtype=float)
YtotS = np.array(S_data[1], dtype=int).reshape(-1, 1) - 1
XtotT = np.array(T_data[0], dtype=float)
YtotT = np.array(T_data[1], dtype=int).reshape(-1, 1) - 1

XS1,yS1,XStest,yStest = get_data(XtotS,YtotS,nbtrain,nbtest,repe)
XT1,yT1,XTtest,yTtest = get_data(XtotT,YtotT,nbtrain,nbtest,repe)

    #XS, yS = generateSubset(XS1, yS1, perClassSource)
    #XT, yT = generateSubset(XT1, yT1, perClassSource)
S = pd.DataFrame(np.c_[XS1, yS1],
                     columns=['X' + str(i) for i in range(XS1.shape[1])] + ['Z'])
T = pd.DataFrame(np.c_[XT1, yT1],
                     columns=['X' + str(i) for i in range(XT1.shape[1])] + ['Z'])
S_test = pd.DataFrame(np.c_[XStest, yStest],
                          columns=['X' + str(i) for i in range(XStest.shape[1])] + ['Z'])
T_test = pd.DataFrame(np.c_[XTtest, yTtest],
                          columns=['X' + str(i) for i in range(XTtest.shape[1])] + ['Z'])


# Exemple de valeurs à tester pour alpha
alpha_values = np.linspace(0, 1, 11)  # 0, 0.1, 0.2, ..., 1.0
best_alpha = None
best_score = -np.inf  # ou 0 selon ta métrique

for a in alpha_values:

    pure_source, pure_target, test_source, test_target = discrete_unsupervised_jdcoot(source, target, source, target, alpha=a)

    score = test_target  
    
    if score > best_score:
        best_score = score
        best_alpha = a

print("Meilleur alpha :", best_alpha)
print("Score associé :", best_score)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
Delta: 0.020070853769768717 	  Loss: 2.1992692919258294 	 Accuracy: 0.13446126447016918
Delta: 0.013934807273575637 	  Loss: 2.1991286543979776 	 Accuracy: 0.13446126447016918
Delta: 0.017891672496933107 	  Loss: 2.1988780462113287 	 Accuracy: 0.13446126447016918
Delta: 0.019324073522942672 	  Loss: 2.1981585946912228 	 Accuracy: 0.13446126447016918
Delta: 0.016070939707578908 	  Loss: 2.197205850945167 	 Accuracy: 0.13446126447016918
Delta: 0.014223091316730711 	  Loss: 2.195257141834942 	 Accuracy: 0.12644701691896706
Delta: 0.01283025365292386 	  Loss: 2.1927323041734317 	 Accuracy: 0.12377560106856635
Delta: 0.013382902991117718 	  Loss: 2.1888384137377126 	 Accuracy: 0.12021371326803205
Delta: 0.014149537744283089 	  Loss: 2.1850826878329803 	 Accuracy: 0.11308993766696349
Delta: 0.015192445211071383 	  Loss: 2.1821262492144773 	 Accuracy: 0.11130899376669635
Delta: 0.01959983195849899 	  Loss: 2.1945266048663825 	 Accuracy: 0.13446126447016918
Delta: 0.016599576975201716 	  Loss: 2.185614541460767 	 Accuracy: 0.23597506678539626
Delta: 0.014937721422469035 	  Loss: 2.1709294667396883 	 Accuracy: 0.25200356188780054
Delta: 0.014432428479450931 	  Loss: 2.145216886087809 	 Accuracy: 0.25022261798753337
Delta: 0.013872267041213259 	  Loss: 2.1052283730725994 	 Accuracy: 0.24487978628673196
Delta: 0.013217464617910185 	  Loss: 2.052236752096772 	 Accuracy: 0.21193232413178986
Delta: 0.013322966373765975 	  Loss: 1.9960842027093006 	 Accuracy: 0.23686553873552982
Delta: 0.013020393340838566 	  Loss: 1.9425137618804948 	 Accuracy: 0.2493321460373998
Delta: 0.012290005408677866 	  Loss: 1.8944934372052256 	 Accuracy: 0.25022261798753337
Delta: 0.01132625319325092 	  Loss: 1.8570782591371606 	 Accuracy: 0.23597506678539626
Delta: 0.020012729479065836 	  Loss: 2.188954783228064 	 Accuracy: 0.20926090828138913
Delta: 0.017170935959320722 	  Loss: 2.1693240153792153 	 Accuracy: 0.2493321460373998
Delta: 0.015649233423631868 	  Loss: 2.1352633640956253 	 Accuracy: 0.30632235084594833
Delta: 0.014570177281765535 	  Loss: 2.0796540591516997 	 Accuracy: 0.3321460373998219
Delta: 0.014341318838911033 	  Loss: 2.0066065212576887 	 Accuracy: 0.352626892252894
Delta: 0.014177826506785115 	  Loss: 1.930226434884947 	 Accuracy: 0.3481745325022262
Delta: 0.013570958871885315 	  Loss: 1.8577815805215017 	 Accuracy: 0.327693677649154
Delta: 0.012441216406866644 	  Loss: 1.798523632713101 	 Accuracy: 0.327693677649154
Delta: 0.010788383332081411 	  Loss: 1.7597536070738287 	 Accuracy: 0.31522707034728403
Delta: 0.009920090977200898 	  Loss: 1.7359279550277305 	 Accuracy: 0.3072128227960819
Delta: 0.02013096115546452 	  Loss: 2.183447977959352 	 Accuracy: 0.2350845948352627
Delta: 0.017199382663933616 	  Loss: 2.1547083119031596 	 Accuracy: 0.25378450578806766
Delta: 0.015565230901948965 	  Loss: 2.113764663013946 	 Accuracy: 0.28227960819234194
Delta: 0.015041493958035852 	  Loss: 2.062908117371864 	 Accuracy: 0.3081032947462155
Delta: 0.015085484427795188 	  Loss: 2.0116539977143173 	 Accuracy: 0.3223508459483526
Delta: 0.013925627445459493 	  Loss: 1.9705055489753711 	 Accuracy: 0.3250222617987533
Delta: 0.012407067575003665 	  Loss: 1.9394751796774445 	 Accuracy: 0.3312555654496883
Delta: 0.011392521477762057 	  Loss: 1.9159435251897783 	 Accuracy: 0.333926981300089
Delta: 0.009629449714409878 	  Loss: 1.898006356850777 	 Accuracy: 0.3446126447016919
Delta: 0.009477869353916705 	  Loss: 1.8865745960516431 	 Accuracy: 0.36153161175422976
Delta: 0.020371366186362403 	  Loss: 2.1772278124214846 	 Accuracy: 0.24487978628673196
Delta: 0.017726509638927374 	  Loss: 2.13458892851199 	 Accuracy: 0.25734639358860195
Delta: 0.015049853842755857 	  Loss: 2.0742919385447216 	 Accuracy: 0.4603739982190561
Delta: 0.016180490630657074 	  Loss: 1.9881327070304555 	 Accuracy: 0.5681211041852182
Delta: 0.015812403657515718 	  Loss: 1.8745710248858898 	 Accuracy: 0.5841495992876224
Delta: 0.013301086594802825 	  Loss: 1.7745225539871876 	 Accuracy: 0.5761353517364203
Delta: 0.011638724241847856 	  Loss: 1.722669603236998 	 Accuracy: 0.5609973285841496
Delta: 0.010513244647368669 	  Loss: 1.6995624208009945 	 Accuracy: 0.5467497773820125
Delta: 0.009877600327932896 	  Loss: 1.6865838620479177 	 Accuracy: 0.5235975066785397

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.008628309091628815 	  Loss: 1.6785895818255219 	 Accuracy: 0.5351736420302761
Delta: 0.020446624782429333 	  Loss: 2.1711228134546348 	 Accuracy: 0.26001780943900266
Delta: 0.017872224851115736 	  Loss: 2.1180715236712526 	 Accuracy: 0.3268032056990205
Delta: 0.01617891022742014 	  Loss: 2.0399759756427 	 Accuracy: 0.43544078361531613
Delta: 0.016106766009112497 	  Loss: 1.93168343221797 	 Accuracy: 0.42030276046304543
Delta: 0.014789515908552351 	  Loss: 1.8255870000728045 	 Accuracy: 0.42920747996438113
Delta: 0.013566441709605468 	  Loss: 1.7577499612888186 	 Accuracy: 0.41406945681211044
Delta: 0.012185246632321416 	  Loss: 1.7174230921505471 	 Accuracy: 0.40872662511130897
Delta: 0.009961890774380144 	  Loss: 1.6930335750589849 	 Accuracy: 0.40160284951024044
Delta: 0.008332848662934144 	  Loss: 1.6801426975241838 	 Accuracy: 0.40694568121104185

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.006645980171424089 	  Loss: 1.6733689802408707 	 Accuracy: 0.39982190560997327
Delta: 0.020696340959246218 	  Loss: 2.1649618238775203 	 Accuracy: 0.24577025823686555
Delta: 0.018011837234799877 	  Loss: 2.100742260483469 	 Accuracy: 0.27070347284060553
Delta: 0.016704976735204036 	  Loss: 2.0195044108722096 	 Accuracy: 0.3472840605520926
Delta: 0.01587392222370451 	  Loss: 1.9398575198820658 	 Accuracy: 0.38201246660730187
Delta: 0.014716509656527831 	  Loss: 1.8843051742426882 	 Accuracy: 0.3633125556544969
Delta: 0.015190502297568756 	  Loss: 1.8341293258313842 	 Accuracy: 0.3348174532502226
Delta: 0.013728420276592301 	  Loss: 1.7807463025776067 	 Accuracy: 0.3107747105966162
Delta: 0.011405375626621717 	  Loss: 1.7444452093654124 	 Accuracy: 0.3081032947462155
Delta: 0.009265589754914589 	  Loss: 1.723047959431587 	 Accuracy: 0.3170080142475512
Delta: 0.008361708987431547 	  Loss: 1.708517045958742 	 Accuracy: 0.31522707034728403
Delta: 0.020760461047763815 	  Loss: 2.158441510384485 	 Accuracy: 0.26001780943900266
Delta: 0.018150797504462596 	  Loss: 2.0820648332324527 	 Accuracy: 0.41585040071237755
Delta: 0.017208247488863255 	  Loss: 1.9787253644073675 	 Accuracy: 0.5325022261798753
Delta: 0.016700227573938627 	  Loss: 1.847236535038195 	 Accuracy: 0.5040071237756011
Delta: 0.014188854646912018 	  Loss: 1.7493160546353557 	 Accuracy: 0.48619768477292963
Delta: 0.012182222775165 	  Loss: 1.7039358075802125 	 Accuracy: 0.4657168299198575
Delta: 0.010465582644941606 	  Loss: 1.6800193166684096 	 Accuracy: 0.4577025823686554
Delta: 0.008237119626463113 	  Loss: 1.6687857283339702 	 Accuracy: 0.45592163846838824

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.006455392921577342 	  Loss: 1.6644867499039577 	 Accuracy: 0.46482635796972394
Delta: 0.005441986906565253 	  Loss: 1.6626001823927108 	 Accuracy: 0.4577025823686554
Delta: 0.020960455248670365 	  Loss: 2.1515632611048563 	 Accuracy: 0.27515583259127335
Delta: 0.01821611969862874 	  Loss: 2.061764475655741 	 Accuracy: 0.35529830810329477
Delta: 0.017394485655850018 	  Loss: 1.9487273017939097 	 Accuracy: 0.333926981300089
Delta: 0.016493847553695717 	  Loss: 1.829521372377532 	 Accuracy: 0.3089937666963491
Delta: 0.013355971630919864 	  Loss: 1.760536531936625 	 Accuracy: 0.3054318788958148
Delta: 0.01212458678771393 	  Loss: 1.7244244980808612 	 Accuracy: 0.31522707034728403
Delta: 0.010418507571825077 	  Loss: 1.7032368171706982 	 Accuracy: 0.3072128227960819
Delta: 0.008506511847634398 	  Loss: 1.6934490330378065 	 Accuracy: 0.3116651825467498
Delta: 0.007248252154569078 	  Loss: 1.6898062252930481 	 Accuracy: 0.3161175422974176

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.005653905899521092 	  Loss: 1.6881844216844801 	 Accuracy: 0.3250222617987533
Delta: 0.0210226161289102 	  Loss: 2.145339081717418 	 Accuracy: 0.2965271593944791
Delta: 0.018523131414265707 	  Loss: 2.042606086725181 	 Accuracy: 0.3312555654496883
Delta: 0.016672562928165553 	  Loss: 1.9310147223854972 	 Accuracy: 0.2858414959928762
Delta: 0.01592465316449665 	  Loss: 1.839633810123288 	 Accuracy: 0.2840605520926091
Delta: 0.014806664067142122 	  Loss: 1.76711422904787 	 Accuracy: 0.2867319679430098
Delta: 0.012373676507967698 	  Loss: 1.7257111944807748 	 Accuracy: 0.29118432769367764
Delta: 0.010299589045498405 	  Loss: 1.7060120664237801 	 Accuracy: 0.2947462154942119
Delta: 0.0088734375497298 	  Loss: 1.6952734304969406 	 Accuracy: 0.2929652715939448

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.0064467002362850875 	  Loss: 1.6916388376151006 	 Accuracy: 0.2840605520926091
Delta: 0.005411496368861437 	  Loss: 1.6901905101803045 	 Accuracy: 0.2902938557435441
Delta: 0.021145035879407744 	  Loss: 2.137406589932832 	 Accuracy: 0.2920747996438112
Delta: 0.01852936073258541 	  Loss: 2.016796308944894 	 Accuracy: 0.3535173642030276
Delta: 0.017274207787774144 	  Loss: 1.8954118367053785 	 Accuracy: 0.3312555654496883
Delta: 0.016158244914877225 	  Loss: 1.7936688233970886 	 Accuracy: 0.3223508459483526
Delta: 0.01417415502039207 	  Loss: 1.7334390766564711 	 Accuracy: 0.333926981300089
Delta: 0.011598835791677429 	  Loss: 1.6988934854018087 	 Accuracy: 0.3285841495992876
Delta: 0.009448213339043604 	  Loss: 1.6804655755655846 	 Accuracy: 0.3348174532502226

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.007832331569469846 	  Loss: 1.6730126709240536 	 Accuracy: 0.3294746215494212
Delta: 0.00603792501236919 	  Loss: 1.6702879658397736 	 Accuracy: 0.3268032056990205
Delta: 0.004625327850154655 	  Loss: 1.6693480294792362 	 Accuracy: 0.3321460373998219
Meilleur alpha : 0.4
Score associé : 0.5351736420302761

In [16]:
results = []
numRepetitions = 10
nbtrain=80
nbtest=20
a= 0.4
n_source = len(source.Z)
n_target = len(target.Z)
prop_target_values_s = [0.01,0.05,0.1,0.2,0.4]
prop_target_values_p = [0.01,0.05,0.1,0.2,0.4]
XtotS = np.array(S_data[0], dtype=float)
YtotS = np.array(S_data[1], dtype=int).reshape(-1, 1) - 1
XtotT = np.array(T_data[0], dtype=float)
YtotT = np.array(T_data[1], dtype=int).reshape(-1, 1) - 1
XtotS.shape
repe=1

In [7]:
XS1,yS1,XStest,yStest = get_data(XtotS,YtotS,nbtrain,nbtest,repe)
XT1,yT1,XTtest,yTtest = get_data(XtotT,YtotT,nbtrain,nbtest,repe)

    #XS, yS = generateSubset(XS1, yS1, perClassSource)
    #XT, yT = generateSubset(XT1, yT1, perClassSource)
S = pd.DataFrame(np.c_[XS1, yS1],
                     columns=['X' + str(i) for i in range(XS1.shape[1])] + ['Z'])
T = pd.DataFrame(np.c_[XT1, yT1],
                     columns=['X' + str(i) for i in range(XT1.shape[1])] + ['Z'])
S_test = pd.DataFrame(np.c_[XStest, yStest],
                          columns=['X' + str(i) for i in range(XStest.shape[1])] + ['Z'])
T_test = pd.DataFrame(np.c_[XTtest, yTtest],
                          columns=['X' + str(i) for i in range(XTtest.shape[1])] + ['Z'])

In [13]:
T['Z'].value_counts()
classes = np.union1d(np.unique(source.Z), np.unique(target.Z))
nClass = len(classes)
nClass
from jdcoot.utils import xcolumns, discrete_classifier, discrete_accuracy

x_source = source.loc[:, xcolumns(source)].values
z_source = source.Z.values

x_target = target.loc[:, xcolumns(target)].values
z_target = target.Z.values

clf = discrete_classifier(target, "relu", "softmax", nClass)

InternalError: cudaSetDevice() on GPU:0 failed. Status: out of memory

In [9]:
discrete_unsupervised_jdcoot(S,T, S_test, T_test,alpha=a)

InternalError: cudaSetDevice() on GPU:0 failed. Status: out of memory

In [24]:
discrete_unsupervised_coot( S, T, S_test, T_test,alpha=a)

Delta:       0.0156361 	 Loss:       2.2010207
Delta:       0.0208233 	 Loss:       2.1663747
Delta:       0.0182178 	 Loss:       2.1294713
Delta:       0.0162790 	 Loss:       2.0961136
Delta:       0.0131377 	 Loss:       2.0713907
Delta:       0.0080867 	 Loss:       2.0659345
Delta:       0.0057522 	 Loss:       2.0649909
Delta:       0.0054997 	 Loss:       2.0646522
Delta:       0.0051974 	 Loss:       2.0643182
Delta:       0.0050661 	 Loss:       2.0640708
Delta:       0.0043271 	 Loss:       2.0638897
Delta:       0.0034496 	 Loss:       2.0636709
Delta:       0.0026599 	 Loss:       2.0635733
Delta:       0.0031707 	 Loss:       2.0635515
Delta:       0.0037098 	 Loss:       2.0635059
Delta:       0.0041243 	 Loss:       2.0634456
Delta:       0.0049578 	 Loss:       2.0633264
Delta:       0.0052853 	 Loss:       2.0631646
Delta:       0.0051491 	 Loss:       2.0629489
Delta:       0.0053762 	 Loss:       2.0627186
Delta:       0.0048121 	 Loss:       2.0625464
Delta:       0.0039196 	 Loss:       2.0624237
Delta:       0.0033052 	 Loss:       2.0623094
Delta:       0.0022714 	 Loss:       2.0622607
Delta:       0.0016636 	 Loss:       2.0622248
Delta:       0.0004920 	 Loss:       2.0622151
Delta:       0.0000013 	 Loss:       2.0622142
Delta:       0.0000000 	 Loss:       2.0622142
converged at iter  27

(1.0, np.float64(0.56125), 1.0, np.float64(0.5705521472392638))

In [63]:
target.shape

(1123, 1025)

In [ ]:
import math

results = []
numRepetitions = 1
nbtrain=800
nbtest=200
a= 0.4
repe=1
n_source = len(source.Z)
n_target = len(target.Z)
prop_target_values_s = [0.01,0.05,0.1,0.2,0.4]
prop_target_values_p = [0.01,0.05,0.1,0.2,0.4]
XtotS = np.array(S_data[0], dtype=float)
YtotS = np.array(S_data[1], dtype=int).reshape(-1, 1) - 1
XtotT = np.array(T_data[0], dtype=float)
YtotT = np.array(T_data[1], dtype=int).reshape(-1, 1) - 1


#for repe in range(numRepetitions):
#    print('num repe :', repe + 1)
XS1,yS1,XStest,yStest = get_data(XtotS,YtotS,nbtrain,nbtest,repe)
XT1,yT1,XTtest,yTtest = get_data(XtotT,YtotT,nbtrain,nbtest,repe)

    #XS, yS = generateSubset(XS1, yS1, perClassSource)
    #XT, yT = generateSubset(XT1, yT1, perClassSource)
S = pd.DataFrame(np.c_[XS1, yS1],
                     columns=['X' + str(i) for i in range(XS1.shape[1])] + ['Z'])
T = pd.DataFrame(np.c_[XT1, yT1],
                     columns=['X' + str(i) for i in range(XT1.shape[1])] + ['Z'])
S_test = pd.DataFrame(np.c_[XStest, yStest],
                          columns=['X' + str(i) for i in range(XStest.shape[1])] + ['Z'])
T_test = pd.DataFrame(np.c_[XTtest, yTtest],
                          columns=['X' + str(i) for i in range(XTtest.shape[1])] + ['Z'])

    # =========================================================
    # UNSUPERVISED
    # =========================================================
#for recoding, func in [
#        ("jdcoot", discrete_unsupervised_jdcoot),
 #       ("coot", discrete_unsupervised_coot),
 #   ]:
pure_source, pure_target, test_source, test_target = discrete_unsupervised_jdcoot(S, T, S, T,alpha=a)

test_target

Delta: 0.020604676069039197 	  Loss: 2.1899771523466036 	 Accuracy: 0.24
Delta: 0.01804443017389411 	  Loss: 2.1461733353112944 	 Accuracy: 0.3425
Delta: 0.01659657501207717 	  Loss: 2.07914864052573 	 Accuracy: 0.37375
Delta: 0.015982322902591748 	  Loss: 1.9802047233556392 	 Accuracy: 0.42375
Delta: 0.014701896401629503 	  Loss: 1.8744333024682578 	 Accuracy: 0.4125
Delta: 0.013089507232964273 	  Loss: 1.792800133240287 	 Accuracy: 0.4175
Delta: 0.012079010558138816 	  Loss: 1.738908967152384 	 Accuracy: 0.42375
Delta: 0.011021812067774339 	  Loss: 1.7065118082858717 	 Accuracy: 0.4175
Delta: 0.00920255247274257 	  Loss: 1.6899054400003721 	 Accuracy: 0.42625
Delta: 0.007746608954590427 	  Loss: 1.6831068115604984 	 Accuracy: 0.43

np.float64(0.43)

In [12]:
pure_source, pure_target, test_source, test_target = discrete_unsupervised_jdcoot(S, T, S, T,alpha=a)

test_target

Delta: 0.020568756714356855 	  Loss: 2.1899736784578447 	 Accuracy: 0.245
Delta: 0.01791652927670536 	  Loss: 2.1458999780142953 	 Accuracy: 0.34
Delta: 0.01672161443362766 	  Loss: 2.079870358259678 	 Accuracy: 0.36125
Delta: 0.015192863173359158 	  Loss: 1.998424922083945 	 Accuracy: 0.365
Delta: 0.013810260779751232 	  Loss: 1.9256867863685372 	 Accuracy: 0.4075
Delta: 0.01251125382340719 	  Loss: 1.8686862672692834 	 Accuracy: 0.3925
Delta: 0.011587098355555648 	  Loss: 1.8272850185496812 	 Accuracy: 0.415
Delta: 0.012273650138915706 	  Loss: 1.7936422427557575 	 Accuracy: 0.4075
Delta: 0.01173483828286506 	  Loss: 1.768925924429328 	 Accuracy: 0.40125
Delta: 0.010004606232456283 	  Loss: 1.754190308943675 	 Accuracy: 0.3875

np.float64(0.3875)

In [26]:
results.append({
            "repetition": repe,
            "recoding": "jdcoot",
            "learning": "unsupervised",
            "prop_source": 1,
            "prop_target": 0,
            "pure_source": pure_source,
            "test_source": test_source,
            "pure_target": pure_target,
            "test_target": test_target,
        })

In [15]:
pure_source, pure_target, test_source, test_target = discrete_unsupervised_coot(S, T, S, T)

Delta:       0.0156422 	 Loss:       2.2021110
Delta:       0.0208768 	 Loss:       2.1691646
Delta:       0.0177753 	 Loss:       2.1349569
Delta:       0.0143025 	 Loss:       2.1204074
Delta:       0.0134693 	 Loss:       2.1127211
Delta:       0.0137265 	 Loss:       2.1037610
Delta:       0.0131059 	 Loss:       2.0941868
Delta:       0.0108799 	 Loss:       2.0876489
Delta:       0.0082359 	 Loss:       2.0847121
Delta:       0.0070575 	 Loss:       2.0836706
Delta:       0.0048615 	 Loss:       2.0831098
Delta:       0.0036876 	 Loss:       2.0830085
Delta:       0.0014327 	 Loss:       2.0829536
Delta:       0.0016584 	 Loss:       2.0829508
Delta:       0.0004895 	 Loss:       2.0829506
Delta:       0.0007728 	 Loss:       2.0829506
converged at iter  15

In [16]:
test_target

np.float64(0.25333333333333335)

In [28]:
df_results = pd.DataFrame(results)
df_results
df_results.to_excel("results_mean.xlsx", index=False)

In [67]:
source=pd.DataFrame(np.concatenate((S_data[0],S_data[1].reshape(-1,1)),axis=1),columns=['X'+str(i) for i in range(S_data[0].shape[1])]+['Z'])
target=pd.DataFrame(np.concatenate((T_data[0],T_data[1].reshape(-1,1)),axis=1),columns=['X'+str(i) for i in range(T_data[0].shape[1])]+['Z'])

source.loc[:,'Z'] = source.loc[:, 'Z'] - 1
target.loc[:,'Z'] = target.loc[:, 'Z'] - 1

a=np.random.choice(np.arange(len(source.index)),math.ceil(0.7*len(source.index)),replace=False)
b=np.random.choice(np.arange(len(target.index)),math.ceil(0.7*len(target.index)),replace=False)
S_test=source.iloc[a,:].reset_index(drop=True)
T_test=target.iloc[b,:].reset_index(drop=True)

S=source.iloc[np.setdiff1d(np.arange(len(source.index)),a),:].reset_index(drop=True)
T=target.iloc[np.setdiff1d(np.arange(len(target.index)),b),:].reset_index(drop=True)
T_test.shape

(787, 1025)

In [47]:
pure_source, pure_target, test_source, test_target = discrete_unsupervised_jdcoot(S, T,  S_test, T_test, alpha=0.66)

Delta: 0.02162954753151638 	  Loss: 2.2064435525074266 	 Accuracy: 0.16964285714285715
Delta: 0.0203060062042208 	  Loss: 2.0866812993621506 	 Accuracy: 0.27380952380952384
Delta: 0.019339676073705025 	  Loss: 1.921979274273892 	 Accuracy: 0.3333333333333333
Delta: 0.017074717446758987 	  Loss: 1.7897524394344986 	 Accuracy: 0.3392857142857143
Delta: 0.014697332874395607 	  Loss: 1.7172567367630043 	 Accuracy: 0.3244047619047619
Delta: 0.012540406545963776 	  Loss: 1.684557033197894 	 Accuracy: 0.31547619047619047
Delta: 0.010926340996103904 	  Loss: 1.6708734630853834 	 Accuracy: 0.3005952380952381
Delta: 0.00981756940332448 	  Loss: 1.6651487778450003 	 Accuracy: 0.30654761904761907
Delta: 0.008811436298066728 	  Loss: 1.66398045165981 	 Accuracy: 0.30357142857142855

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.007396354431511463 	  Loss: 1.6635911540376345 	 Accuracy: 0.30357142857142855

In [20]:
import math
results = []
numRepetitions = 10
a = 0.5

prop_target_values_s = [0.01, 0.05, 0.1, 0.2, 0.4]
prop_target_values_p = [0.01, 0.05, 0.1, 0.2, 0.4]



source=pd.DataFrame(np.concatenate((S_data[0],S_data[1].reshape(-1,1)),axis=1),columns=['X'+str(i) for i in range(S_data[0].shape[1])]+['Z'])
target=pd.DataFrame(np.concatenate((T_data[0],T_data[1].reshape(-1,1)),axis=1),columns=['X'+str(i) for i in range(T_data[0].shape[1])]+['Z'])

source.loc[:,'Z'] = source.loc[:, 'Z'] - 1
target.loc[:,'Z'] = target.loc[:, 'Z'] - 1

for repe in range(numRepetitions):
    print("num repe :", repe + 1)

    a=np.random.choice(np.arange(len(source.index)),math.ceil(0.7*len(source.index)),replace=False)
    b=np.random.choice(np.arange(len(target.index)),math.ceil(0.7*len(target.index)),replace=False)
    S=source.iloc[a,:].reset_index(drop=True)
    T=target.iloc[b,:].reset_index(drop=True)

    S_test=source.iloc[np.setdiff1d(np.arange(len(source.index)),a),:].reset_index(drop=True)
    T_test=target.iloc[np.setdiff1d(np.arange(len(target.index)),b),:].reset_index(drop=True)
    # =========================================================
    # UNSUPERVISED
    # =========================================================

    # COOT (sans alpha)
    pure_source, pure_target, test_source, test_target = discrete_unsupervised_coot(S, T, S_test, T_test)

    results.append({
        "repetition": repe,
        "recoding": "coot",
        "learning": "unsupervised",
        "prop_source": 1,
        "prop_target": 0,
        "pure_source": pure_source,
        "test_source": test_source,
        "pure_target": pure_target,
        "test_target": test_target,
    })

    # JDCOOT
    pure_source, pure_target, test_source, test_target = discrete_unsupervised_jdcoot(S, T,  S_test, T_test, alpha = 0.4)

    results.append({
        "repetition": repe,
        "recoding": "jdcoot",
        "learning": "unsupervised",
        "prop_source": 1,
        "prop_target": 0,
        "pure_source": pure_source,
        "test_source": test_source,
        "pure_target": pure_target,
        "test_target": test_target,
    })

   

df_results = pd.DataFrame(results)


df_results

df_summary = (
    df_results
    .groupby(
        ["recoding", "learning", "prop_source", "prop_target"],
        as_index=False
    )
    .agg(
        pure_source_mean=("pure_source", "mean"),
        pure_source_var=("pure_source", "var"),
        test_source_mean=("test_source", "mean"),
        test_source_var=("test_source", "var"),
        pure_target_mean=("pure_target", "mean"),
        pure_target_var=("pure_target", "var"),
        test_target_mean=("test_target", "mean"),
        test_target_var=("test_target", "var"),
    )
)

num repe : 1
Delta:       0.0156359 	 Loss:       2.2044734
Delta:       0.0209840 	 Loss:       2.1662393
Delta:       0.0185675 	 Loss:       2.1072568
Delta:       0.0146230 	 Loss:       2.0754322
Delta:       0.0112744 	 Loss:       2.0663307
Delta:       0.0085521 	 Loss:       2.0641118
Delta:       0.0071566 	 Loss:       2.0633101
Delta:       0.0063113 	 Loss:       2.0629898
Delta:       0.0058049 	 Loss:       2.0627484
Delta:       0.0047601 	 Loss:       2.0626239
Delta: 0.020483176888626983 	  Loss: 2.1909931176359447 	 Accuracy: 0.10581222056631892
Delta: 0.016912573173977947 	  Loss: 2.1694329823388045 	 Accuracy: 0.15648286140089418
Delta: 0.013698297827186042 	  Loss: 2.150870650525441 	 Accuracy: 0.17585692995529062
Delta: 0.012296416885201035 	  Loss: 2.137754422014215 	 Accuracy: 0.2488822652757079
Delta: 0.010050267048937023 	  Loss: 2.130399160342897 	 Accuracy: 0.29806259314456035
Delta: 0.00876778297624606 	  Loss: 2.1260583554748225 	 Accuracy: 0.30998509687034276
Delta: 0.008163999220882198 	  Loss: 2.1240642592402894 	 Accuracy: 0.3204172876304024
Delta: 0.007504820486505725 	  Loss: 2.1230836580720154 	 Accuracy: 0.3293591654247392
Delta: 0.00695798304483619 	  Loss: 2.1217484038579664 	 Accuracy: 0.3323397913561848
Delta: 0.006296648783767158 	  Loss: 2.1211574837986085 	 Accuracy: 0.3174366616989568
num repe : 2
Delta:       0.0156365 	 Loss:       2.2073115
Delta:       0.0210565 	 Loss:       2.1678065
Delta:       0.0185370 	 Loss:       2.1132904
Delta:       0.0151008 	 Loss:       2.0776877
Delta:       0.0132918 	 Loss:       2.0645875
Delta:       0.0115828 	 Loss:       2.0562454
Delta:       0.0096842 	 Loss:       2.0529458
Delta:       0.0068526 	 Loss:       2.0518200
Delta:       0.0058888 	 Loss:       2.0515687
Delta:       0.0059199 	 Loss:       2.0513077
Delta: 0.020432333718851028 	  Loss: 2.1932968460764224 	 Accuracy: 0.23845007451564829
Delta: 0.01690950749247665 	  Loss: 2.17262170699244 	 Accuracy: 0.2846497764530551
Delta: 0.01365598206400458 	  Loss: 2.157437198598119 	 Accuracy: 0.30849478390462
Delta: 0.012290629476247863 	  Loss: 2.146336423387358 	 Accuracy: 0.3323397913561848
Delta: 0.01187096708878193 	  Loss: 2.1376032734329034 	 Accuracy: 0.3174366616989568
Delta: 0.010802629948301426 	  Loss: 2.130700486085331 	 Accuracy: 0.3144560357675112
Delta: 0.009547518362934156 	  Loss: 2.1261804828295787 	 Accuracy: 0.3055141579731744
Delta: 0.009122008068760262 	  Loss: 2.1233869971353934 	 Accuracy: 0.3055141579731744
Delta: 0.008284061576647114 	  Loss: 2.121278498023001 	 Accuracy: 0.30700447093889716
Delta: 0.007404145516442165 	  Loss: 2.120028287896627 	 Accuracy: 0.30402384500745155
num repe : 3
Delta:       0.0156363 	 Loss:       2.1985282
Delta:       0.0209131 	 Loss:       2.1624282
Delta:       0.0187071 	 Loss:       2.1029361
Delta:       0.0149152 	 Loss:       2.0630843
Delta:       0.0119624 	 Loss:       2.0526554
Delta:       0.0103983 	 Loss:       2.0482855
Delta:       0.0085980 	 Loss:       2.0454829
Delta:       0.0066411 	 Loss:       2.0443450
Delta:       0.0059201 	 Loss:       2.0439274
Delta:       0.0050833 	 Loss:       2.0434337
Delta: 0.02044054135978132 	  Loss: 2.1854382023199754 	 Accuracy: 0.18181818181818182
Delta: 0.01723795345648555 	  Loss: 2.163856395257588 	 Accuracy: 0.22354694485842028
Delta: 0.014236917688558084 	  Loss: 2.142264572710977 	 Accuracy: 0.2816691505216095
Delta: 0.011788021878366979 	  Loss: 2.1252696965156908 	 Accuracy: 0.2846497764530551
Delta: 0.010005539390724027 	  Loss: 2.114259632477815 	 Accuracy: 0.30104321907600595
Delta: 0.009276294119145486 	  Loss: 2.1077230436138135 	 Accuracy: 0.3412816691505216
Delta: 0.008615633245197579 	  Loss: 2.1040831639432955 	 Accuracy: 0.35171385991058124
Delta: 0.007678532044788972 	  Loss: 2.1014012717286077 	 Accuracy: 0.3621460506706408
Delta: 0.006110483695138625 	  Loss: 2.0997413247338086 	 Accuracy: 0.3591654247391952
Delta: 0.005497589965667351 	  Loss: 2.099215851352809 	 Accuracy: 0.3621460506706408
num repe : 4
Delta:       0.0156364 	 Loss:       2.2094169
Delta:       0.0209217 	 Loss:       2.1734477
Delta:       0.0183067 	 Loss:       2.1266028
Delta:       0.0149089 	 Loss:       2.0984585
Delta:       0.0126328 	 Loss:       2.0829877
Delta:       0.0096057 	 Loss:       2.0763244
Delta:       0.0074096 	 Loss:       2.0742336
Delta:       0.0054307 	 Loss:       2.0733486
Delta:       0.0035001 	 Loss:       2.0732175
Delta:       0.0019940 	 Loss:       2.0731635
Delta: 0.020400131125433162 	  Loss: 2.196889756216601 	 Accuracy: 0.19225037257824143
Delta: 0.017252753957447693 	  Loss: 2.176781885997478 	 Accuracy: 0.20119225037257824
Delta: 0.014348006430408502 	  Loss: 2.159031820867095 	 Accuracy: 0.28315946348733234
Delta: 0.011440928011651978 	  Loss: 2.145820388076686 	 Accuracy: 0.37555886736214605
Delta: 0.010117673829422517 	  Loss: 2.136858608670822 	 Accuracy: 0.4217585692995529
Delta: 0.009183826150862077 	  Loss: 2.130620577826633 	 Accuracy: 0.4456035767511177
Delta: 0.008224248312375853 	  Loss: 2.126369544691488 	 Accuracy: 0.43815201192250375

KeyboardInterrupt:

In [ ]:
 # =========================================================
    # SEMI-SUPERVISED
    # =========================================================
    for prop_target in prop_target_values_s:

        # JDCOOT
        pure_source, pure_target, test_source, test_target = discrete_semisupervised_jdcoot(
                S, T, S_test, T_test,
                alpha=0.5,
                prop_target=prop_target
            )

        results.append({
            "repetition": repe,
            "recoding": "jdcoot",
            "learning": "semisupervised",
            "prop_source": 1,
            "prop_target": prop_target,
            "pure_source": pure_source,
            "test_source": test_source,
            "pure_target": pure_target,
            "test_target": test_target,
        })

        # COOT
        pure_source, pure_target, test_source, test_target = \
            discrete_semisupervised_coot(
                S, T, S_test, T_test,
                prop_target=prop_target
            )

        results.append({
            "repetition": repe,
            "recoding": "coot",
            "learning": "semisupervised",
            "prop_source": 1,
            "prop_target": prop_target,
            "pure_source": pure_source,
            "test_source": test_source,
            "pure_target": pure_target,
            "test_target": test_target,
        })

        # Reference
        pure_source, pure_target, test_source, test_target = discrete_semisupervised_reference(
                S, T, S_test, T_test,
                prop_target=prop_target
            )

        results.append({
            "repetition": repe,
            "recoding": "reference",
            "learning": "semisupervised",
            "prop_source": 1,
            "prop_target": prop_target,
            "pure_source": pure_source,
            "test_source": test_source,
            "pure_target": pure_target,
            "test_target": test_target,
        })

    # =========================================================
    # PARTIAL
    # =========================================================
    for prop_target in prop_target_values_p:

        # JDCOOT
        pure_source, pure_target, test_source, test_target = discrete_partial_jdcoot(
                S, T, S_test, T_test,
                alpha=0.5,
                prop_source=0.5,
                prop_target=prop_target
            )

        results.append({
            "repetition": repe,
            "recoding": "jdcoot",
            "learning": "partial",
            "prop_source": 0.5,
            "prop_target": prop_target,
            "pure_source": pure_source,
            "test_source": test_source,
            "pure_target": pure_target,
            "test_target": test_target,
        })

        # COOT
        pure_source, pure_target, test_source, test_target = discrete_partial_coot(
                S, T, S_test, T_test,
                prop_source=0.5,
                prop_target=prop_target
            )

        results.append({
            "repetition": repe,
            "recoding": "coot",
            "learning": "partial",
            "prop_source": 0.5,
            "prop_target": prop_target,
            "pure_source": pure_source,
            "test_source": test_source,
            "pure_target": pure_target,
            "test_target": test_target,
        })

        # Reference
        pure_source, pure_target, test_source, test_target = discrete_partial_reference(
                S, T, S_test, T_test,
                prop_source=0.5,
                prop_target=prop_target
            )

        results.append({
            "repetition": repe,
            "recoding": "reference",
            "learning": "partial",
            "prop_source": 0.5,
            "prop_target": prop_target,
            "pure_source": pure_source,
            "test_source": test_source,
            "pure_target": pure_target,
            "test_target": test_target,
        })

In [77]:
df_summary

,recoding,learning,prop_source,prop_target,pure_source_mean,pure_source_var,test_source_mean,test_source_var,pure_target_mean,pure_target_var,test_target_mean,test_target_var
0,coot,unsupervised,1,0,1.0,0.0,1.0,0.0,0.405591,0.019907,0.414881,0.022938
1,jdcoot,unsupervised,1,0,1.0,0.0,1.0,0.0,0.317662,0.031219,0.325595,0.030766

In [ ]:
results = []
numRepetitions = 10
nbtrain = 80
nbtest = 20
a = 0.01

prop_target_values_s = [0.01, 0.05, 0.1, 0.2, 0.4]
prop_target_values_p = [0.01, 0.05, 0.1, 0.2, 0.4]

XtotS = np.array(S_data[0], dtype=float)
YtotS = np.array(S_data[1], dtype=int).reshape(-1, 1) - 1

XtotT = np.array(T_data[0], dtype=float)
YtotT = np.array(T_data[1], dtype=int).reshape(-1, 1) - 1

for repe in range(numRepetitions):
    print("num repe :", repe + 1)

    XS1, yS1, XStest, yStest = get_data_2(XtotS, YtotS, nbtrain, nbtest, repe)
    XT1, yT1, XTtest, yTtest = get_data_2(XtotT, YtotT, nbtrain, nbtest, repe)

    S = pd.DataFrame(
        np.c_[XS1, yS1],
        columns=[f"X{i}" for i in range(XS1.shape[1])] + ["Z"]
    )

    T = pd.DataFrame(
        np.c_[XT1, yT1],
        columns=[f"X{i}" for i in range(XT1.shape[1])] + ["Z"]
    )

    S_test = pd.DataFrame(
        np.c_[XStest, yStest],
        columns=[f"X{i}" for i in range(XStest.shape[1])] + ["Z"]
    )

    T_test = pd.DataFrame(
        np.c_[XTtest, yTtest],
        columns=[f"X{i}" for i in range(XTtest.shape[1])] + ["Z"]
    )

    # =========================================================
    # UNSUPERVISED
    # =========================================================

    # JDCOOT
    pure_source, pure_target, test_source, test_target = discrete_unsupervised_jdcoot(S, T, S, T, alpha=a)

    results.append({
        "repetition": repe,
        "recoding": "jdcoot",
        "learning": "unsupervised",
        "prop_source": 1,
        "prop_target": 0,
        "pure_source": pure_source,
        "test_source": test_source,
        "pure_target": pure_target,
        "test_target": test_target,
    })

    # COOT (sans alpha)
    pure_source, pure_target, test_source, test_target = discrete_unsupervised_coot(S, T, S, T)

    results.append({
        "repetition": repe,
        "recoding": "coot",
        "learning": "unsupervised",
        "prop_source": 1,
        "prop_target": 0,
        "pure_source": pure_source,
        "test_source": test_source,
        "pure_target": pure_target,
        "test_target": test_target,
    })

 
import pandas as pd

df_results = pd.DataFrame(results)


df_results

df_summary = (
    df_results
    .groupby(
        ["recoding", "learning", "prop_source", "prop_target"],
        as_index=False
    )
    .agg(
        pure_source_mean=("pure_source", "mean"),
        pure_source_var=("pure_source", "var"),
        test_source_mean=("test_source", "mean"),
        test_source_var=("test_source", "var"),
        pure_target_mean=("pure_target", "mean"),
        pure_target_var=("pure_target", "var"),
        test_target_mean=("test_target", "mean"),
        test_target_var=("test_target", "var"),
    )
)
df_summary

num repe : 1
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
Delta: 0.0630407778513002 	  Loss: 1.8134424277156618 	 Accuracy: 0.1475
Delta: 0.051077024143968155 	  Loss: 1.7653979809586575 	 Accuracy: 0.145
Delta: 0.04172664749744727 	  Loss: 1.7461373861218679 	 Accuracy: 0.145
Delta: 0.03343335782028892 	  Loss: 1.7374525440389796 	 Accuracy: 0.145
Delta: 0.02559224042786981 	  Loss: 1.7350510020918537 	 Accuracy: 0.145
Delta: 0.025615296761164745 	  Loss: 1.732599169907346 	 Accuracy: 0.145
Delta: 0.02056974390388626 	  Loss: 1.7317195093896662 	 Accuracy: 0.145
Delta: 0.01872108461966716 	  Loss: 1.7311238297191918 	 Accuracy: 0.145
Delta: 0.013198731785563807 	  Loss: 1.7310184241670092 	 Accuracy: 0.145
Delta: 0.01322770690255867 	  Loss: 1.730984957432514 	 Accuracy: 0.145
Delta:       0.0509506 	 Loss:       1.9609350
Delta:       0.0670170 	 Loss:       1.5919715
Delta:       0.0585432 	 Loss:       1.4756371
Delta:       0.0493188 	 Loss:       1.4333216
Delta:       0.0484531 	 Loss:       1.3885664
Delta:       0.0453111 	 Loss:       1.3521455
Delta:       0.0365951 	 Loss:       1.3423907
Delta:       0.0307474 	 Loss:       1.3379079
Delta:       0.0231084 	 Loss:       1.3365828
Delta:       0.0192155 	 Loss:       1.3360871
Delta:       0.0185169 	 Loss:       1.3354964
Delta:       0.0177745 	 Loss:       1.3349838
Delta:       0.0144181 	 Loss:       1.3347787
Delta:       0.0113299 	 Loss:       1.3347345
Delta:       0.0126053 	 Loss:       1.3346971
Delta:       0.0126328 	 Loss:       1.3345744
Delta:       0.0072887 	 Loss:       1.3345744
converged at iter  16
num repe : 2
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
Delta: 0.06280791172534178 	  Loss: 1.7846429270635793 	 Accuracy: 0.125
Delta: 0.04795212459602741 	  Loss: 1.7450133964120158 	 Accuracy: 0.1275
Delta: 0.03756639796735746 	  Loss: 1.7319357428538935 	 Accuracy: 0.1275
Delta: 0.031961956752897376 	  Loss: 1.725942690188556 	 Accuracy: 0.1275
Delta: 0.029595906312156823 	  Loss: 1.7221264473761702 	 Accuracy: 0.1275
Delta: 0.021241817070512196 	  Loss: 1.7210793939218212 	 Accuracy: 0.1275
Delta: 0.017690887913377754 	  Loss: 1.720631794159321 	 Accuracy: 0.1275
Delta: 0.016620809923467084 	  Loss: 1.7201612443060639 	 Accuracy: 0.1275
Delta: 0.01704725481522477 	  Loss: 1.719504269926928 	 Accuracy: 0.1275
Delta: 0.013818346008574798 	  Loss: 1.719454244461848 	 Accuracy: 0.1275
Delta:       0.0509506 	 Loss:       1.9551498
Delta:       0.0675943 	 Loss:       1.5671207
Delta:       0.0600901 	 Loss:       1.4050560
Delta:       0.0462719 	 Loss:       1.3831479
Delta:       0.0359360 	 Loss:       1.3757912
Delta:       0.0303829 	 Loss:       1.3702592
Delta:       0.0310241 	 Loss:       1.3657792
Delta:       0.0294851 	 Loss:       1.3621912
Delta:       0.0252290 	 Loss:       1.3598112
Delta:       0.0205341 	 Loss:       1.3588066
Delta:       0.0169670 	 Loss:       1.3583614
Delta:       0.0160148 	 Loss:       1.3582354
Delta:       0.0135917 	 Loss:       1.3581762
Delta:       0.0144780 	 Loss:       1.3579706
Delta:       0.0148061 	 Loss:       1.3577773
Delta:       0.0115036 	 Loss:       1.3577677
Delta:       0.0094171 	 Loss:       1.3577644
Delta:       0.0079057 	 Loss:       1.3577644
converged at iter  17
num repe : 3
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
Delta: 0.06177796057035622 	  Loss: 1.8053701572372316 	 Accuracy: 0.1025
Delta: 0.04783286090322231 	  Loss: 1.7730660115815917 	 Accuracy: 0.10625
Delta: 0.035352544890471745 	  Loss: 1.7634537160285253 	 Accuracy: 0.10625
Delta: 0.02940485248073231 	  Loss: 1.7585154008210029 	 Accuracy: 0.10625
Delta: 0.022871292357961922 	  Loss: 1.7565741247348794 	 Accuracy: 0.10625
Delta: 0.02319974183689626 	  Loss: 1.7546758094091575 	 Accuracy: 0.10625
Delta: 0.021123914761424424 	  Loss: 1.753310935328263 	 Accuracy: 0.10625
Delta: 0.018426727390672706 	  Loss: 1.7526640140889957 	 Accuracy: 0.10625
Delta: 0.01683400386153447 	  Loss: 1.7519892937949493 	 Accuracy: 0.10625
Delta: 0.016582365783949865 	  Loss: 1.7514063452690536 	 Accuracy: 0.10625
Delta:       0.0509506 	 Loss:       1.9482428
Delta:       0.0670739 	 Loss:       1.5578951
Delta:       0.0594572 	 Loss:       1.4373992
Delta:       0.0467454 	 Loss:       1.4115565
Delta:       0.0411786 	 Loss:       1.3949433
Delta:       0.0366542 	 Loss:       1.3822421
Delta:       0.0361835 	 Loss:       1.3726152
Delta:       0.0299141 	 Loss:       1.3675623
Delta:       0.0240804 	 Loss:       1.3658257
Delta:       0.0169890 	 Loss:       1.3652950
Delta:       0.0206213 	 Loss:       1.3641594
Delta:       0.0199000 	 Loss:       1.3633398
Delta:       0.0179540 	 Loss:       1.3628563
Delta:       0.0132350 	 Loss:       1.3627366
Delta:       0.0142321 	 Loss:       1.3625620
Delta:       0.0159249 	 Loss:       1.3621837
Delta:       0.0187600 	 Loss:       1.3615918
Delta:       0.0185146 	 Loss:       1.3611682
Delta:       0.0146739 	 Loss:       1.3610284
Delta:       0.0166635 	 Loss:       1.3608051
Delta:       0.0120262 	 Loss:       1.3607924
Delta:       0.0058630 	 Loss:       1.3607924
converged at iter  21
num repe : 4
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
Delta: 0.06268617209317932 	  Loss: 1.810788941781163 	 Accuracy: 0.11625
Delta: 0.04800740178915361 	  Loss: 1.7774828647722214 	 Accuracy: 0.11875
Delta: 0.03900890111941499 	  Loss: 1.764814818196193 	 Accuracy: 0.11875
Delta: 0.029070308213938266 	  Loss: 1.760406082558458 	 Accuracy: 0.11875
Delta: 0.02797135447374812 	  Loss: 1.756169496011318 	 Accuracy: 0.11875
Delta: 0.026705013040840782 	  Loss: 1.752744856791997 	 Accuracy: 0.11875
Delta: 0.02016238097163409 	  Loss: 1.7515467757719403 	 Accuracy: 0.11875
Delta: 0.02124428747011134 	  Loss: 1.7507011266472612 	 Accuracy: 0.11875
Delta: 0.019942917346169958 	  Loss: 1.7497923398675055 	 Accuracy: 0.11875
Delta: 0.017042092334890603 	  Loss: 1.749371364138714 	 Accuracy: 0.11875
Delta:       0.0509506 	 Loss:       1.9444339
Delta:       0.0663542 	 Loss:       1.6370393
Delta:       0.0609318 	 Loss:       1.4788164
Delta:       0.0526420 	 Loss:       1.4198763
Delta:       0.0440446 	 Loss:       1.3967705
Delta:       0.0356270 	 Loss:       1.3885024
Delta:       0.0362803 	 Loss:       1.3806656
Delta:       0.0306642 	 Loss:       1.3757727
Delta:       0.0286026 	 Loss:       1.3707320
Delta:       0.0302011 	 Loss:       1.3649992
Delta:       0.0292875 	 Loss:       1.3598983
Delta:       0.0283046 	 Loss:       1.3564174
Delta:       0.0273074 	 Loss:       1.3542693
Delta:       0.0269712 	 Loss:       1.3520480
Delta:       0.0236455 	 Loss:       1.3503539
Delta:       0.0187605 	 Loss:       1.3498601
Delta:       0.0193755 	 Loss:       1.3491999
Delta:       0.0210180 	 Loss:       1.3482943
Delta:       0.0200310 	 Loss:       1.3477302
Delta:       0.0149841 	 Loss:       1.3475781
Delta:       0.0098948 	 Loss:       1.3475536
Delta:       0.0066144 	 Loss:       1.3475536
converged at iter  21
num repe : 5
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
Delta: 0.06241850068608833 	  Loss: 1.8176796872521424 	 Accuracy: 0.13
Delta: 0.05026407382425719 	  Loss: 1.778673248780144 	 Accuracy: 0.13
Delta: 0.03733593349453993 	  Loss: 1.7662827707871835 	 Accuracy: 0.13
Delta: 0.03065244726974953 	  Loss: 1.7596626214791937 	 Accuracy: 0.13
Delta: 0.025402766296814653 	  Loss: 1.7569582820692884 	 Accuracy: 0.13
Delta: 0.023191819702271303 	  Loss: 1.7555147679428407 	 Accuracy: 0.13
Delta: 0.01934765983641252 	  Loss: 1.7546182392478038 	 Accuracy: 0.13
Delta: 0.016368524741314026 	  Loss: 1.7543519038205266 	 Accuracy: 0.13
Delta: 0.018953559117001993 	  Loss: 1.7529884160823708 	 Accuracy: 0.13
Delta: 0.02226131043410276 	  Loss: 1.7512268818044214 	 Accuracy: 0.13
Delta:       0.0509506 	 Loss:       1.9595123
Delta:       0.0656753 	 Loss:       1.6244657
Delta:       0.0605761 	 Loss:       1.4619541
Delta:       0.0512489 	 Loss:       1.4151589
Delta:       0.0432204 	 Loss:       1.3990985
Delta:       0.0335741 	 Loss:       1.3937302
Delta:       0.0258089 	 Loss:       1.3913013
Delta:       0.0269835 	 Loss:       1.3890512
Delta:       0.0230550 	 Loss:       1.3875678
Delta:       0.0170197 	 Loss:       1.3873270
Delta:       0.0204149 	 Loss:       1.3860668
Delta:       0.0158083 	 Loss:       1.3859358
Delta:       0.0113797 	 Loss:       1.3859234
Delta:       0.0070711 	 Loss:       1.3859234
converged at iter  13
num repe : 6
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
Delta: 0.06223778615264319 	  Loss: 1.8280291202361796 	 Accuracy: 0.12
Delta: 0.047557540789762584 	  Loss: 1.7952229397990398 	 Accuracy: 0.1225
Delta: 0.03594887403262975 	  Loss: 1.7848789443795985 	 Accuracy: 0.12125
Delta: 0.02987298046980842 	  Loss: 1.7789201896000337 	 Accuracy: 0.12125
Delta: 0.027090015830047807 	  Loss: 1.774840350911679 	 Accuracy: 0.12125
Delta: 0.02386401883182005 	  Loss: 1.7724175036388525 	 Accuracy: 0.12125
Delta: 0.02467329352114357 	  Loss: 1.7711970519917954 	 Accuracy: 0.12125
Delta: 0.020230023966039297 	  Loss: 1.769924833844664 	 Accuracy: 0.12125
Delta: 0.017207377802736533 	  Loss: 1.7694348177834764 	 Accuracy: 0.12125
Delta: 0.011599025619931012 	  Loss: 1.769366643829704 	 Accuracy: 0.12125
Delta:       0.0509506 	 Loss:       1.9540613
Delta:       0.0665258 	 Loss:       1.6072819
Delta:       0.0608831 	 Loss:       1.4572881
Delta:       0.0521936 	 Loss:       1.4072832
Delta:       0.0425841 	 Loss:       1.3907988
Delta:       0.0357567 	 Loss:       1.3821024
Delta:       0.0332058 	 Loss:       1.3737759
Delta:       0.0305882 	 Loss:       1.3673231
Delta:       0.0306384 	 Loss:       1.3628432
Delta:       0.0259487 	 Loss:       1.3601334
Delta:       0.0226100 	 Loss:       1.3587210
Delta:       0.0222872 	 Loss:       1.3571984
Delta:       0.0151358 	 Loss:       1.3570374
Delta:       0.0181858 	 Loss:       1.3563882
Delta:       0.0170154 	 Loss:       1.3560542
Delta:       0.0152478 	 Loss:       1.3557982
Delta:       0.0108582 	 Loss:       1.3557860
Delta:       0.0117908 	 Loss:       1.3557430
Delta:       0.0072887 	 Loss:       1.3557430
converged at iter  18
num repe : 7
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
Delta: 0.062250668585365695 	  Loss: 1.8003593015314299 	 Accuracy: 0.14375
Delta: 0.04744157433624871 	  Loss: 1.7674059524751329 	 Accuracy: 0.14625
Delta: 0.038387205165321306 	  Loss: 1.753956397223582 	 Accuracy: 0.14625
Delta: 0.025420812571260304 	  Loss: 1.750867880957679 	 Accuracy: 0.14625
Delta: 0.0236408637536661 	  Loss: 1.748544980930259 	 Accuracy: 0.14625
Delta: 0.020775723478098924 	  Loss: 1.7471097538876141 	 Accuracy: 0.14625
Delta: 0.016336736067557454 	  Loss: 1.7466934225791546 	 Accuracy: 0.14625
Delta: 0.017642810469969985 	  Loss: 1.746046920837915 	 Accuracy: 0.14625
Delta: 0.0147601942797412 	  Loss: 1.7457152984953765 	 Accuracy: 0.14625
Delta: 0.016699112595596626 	  Loss: 1.7453643386309337 	 Accuracy: 0.14625
Delta:       0.0509506 	 Loss:       1.9530169
Delta:       0.0670487 	 Loss:       1.5752181
Delta:       0.0586752 	 Loss:       1.4552019
Delta:       0.0481455 	 Loss:       1.4147493
Delta:       0.0467393 	 Loss:       1.3661173
Delta:       0.0423301 	 Loss:       1.3380468
Delta:       0.0351178 	 Loss:       1.3301104
Delta:       0.0279399 	 Loss:       1.3270546
Delta:       0.0259860 	 Loss:       1.3249934
Delta:       0.0243163 	 Loss:       1.3236550
Delta:       0.0164207 	 Loss:       1.3234042
Delta:       0.0146676 	 Loss:       1.3231658
Delta:       0.0100837 	 Loss:       1.3231627
Delta:       0.0110322 	 Loss:       1.3231464
Delta:       0.0113299 	 Loss:       1.3231233
Delta:       0.0112143 	 Loss:       1.3231071
Delta:       0.0075000 	 Loss:       1.3231071
converged at iter  16
num repe : 8
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
Delta: 0.06242694962957511 	  Loss: 1.8059048505995423 	 Accuracy: 0.105
Delta: 0.048285262471558364 	  Loss: 1.7664711587602762 	 Accuracy: 0.10875
Delta: 0.036219396931286264 	  Loss: 1.7565215012899087 	 Accuracy: 0.10875
Delta: 0.03291862772544724 	  Loss: 1.7498181471303136 	 Accuracy: 0.10875
Delta: 0.023930496536458026 	  Loss: 1.746831824638552 	 Accuracy: 0.10875
Delta: 0.02345653248159879 	  Loss: 1.7446583668489004 	 Accuracy: 0.10875
Delta: 0.020237936880773272 	  Loss: 1.7437874802247237 	 Accuracy: 0.10875
Delta: 0.01250211972646232 	  Loss: 1.743696901809318 	 Accuracy: 0.10875
Delta: 0.014262733489430489 	  Loss: 1.743368601652638 	 Accuracy: 0.10875
Delta: 0.006373774391990982 	  Loss: 1.743368601652638 	 Accuracy: 0.10875
converged at iter  9
Delta:       0.0509506 	 Loss:       1.9546499
Delta:       0.0663425 	 Loss:       1.6294712
Delta:       0.0589935 	 Loss:       1.4950622
Delta:       0.0535743 	 Loss:       1.4167595
Delta:       0.0437157 	 Loss:       1.3946815
Delta:       0.0363813 	 Loss:       1.3827375
Delta:       0.0358185 	 Loss:       1.3675316
Delta:       0.0369166 	 Loss:       1.3517715
Delta:       0.0308473 	 Loss:       1.3471034
Delta:       0.0250938 	 Loss:       1.3459830
Delta:       0.0187850 	 Loss:       1.3454291
Delta:       0.0136181 	 Loss:       1.3452970
Delta:       0.0127327 	 Loss:       1.3452158
Delta:       0.0125617 	 Loss:       1.3450110
Delta:       0.0104906 	 Loss:       1.3449721
Delta:       0.0120607 	 Loss:       1.3449414
Delta:       0.0075048 	 Loss:       1.3449412
Delta:       0.0063738 	 Loss:       1.3449412
converged at iter  17
num repe : 9
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
Delta: 0.06310873787987176 	  Loss: 1.7730172593447682 	 Accuracy: 0.12875
Delta: 0.05008780187271273 	  Loss: 1.7282652239296974 	 Accuracy: 0.12875
Delta: 0.03812246655988414 	  Loss: 1.7172332064726774 	 Accuracy: 0.1275
Delta: 0.02691368962968505 	  Loss: 1.7142166948628823 	 Accuracy: 0.1275
Delta: 0.018058570494192724 	  Loss: 1.713530261491771 	 Accuracy: 0.12875
Delta: 0.0208250528747869 	  Loss: 1.712047979802116 	 Accuracy: 0.12875
Delta: 0.017572296103159583 	  Loss: 1.7115803471859667 	 Accuracy: 0.13
Delta: 0.015065302694666643 	  Loss: 1.7111602612966585 	 Accuracy: 0.1275
Delta: 0.01831928189305764 	  Loss: 1.7105020388746788 	 Accuracy: 0.12875
Delta: 0.0192837532364482 	  Loss: 1.7095623492280232 	 Accuracy: 0.13
Delta:       0.0509506 	 Loss:       1.9496977
Delta:       0.0666992 	 Loss:       1.6064841
Delta:       0.0603193 	 Loss:       1.4707194
Delta:       0.0518797 	 Loss:       1.4239077
Delta:       0.0399064 	 Loss:       1.4086716
Delta:       0.0384477 	 Loss:       1.3967039
Delta:       0.0384199 	 Loss:       1.3810170
Delta:       0.0385857 	 Loss:       1.3672087
Delta:       0.0329962 	 Loss:       1.3609058
Delta:       0.0281239 	 Loss:       1.3577619
Delta:       0.0238711 	 Loss:       1.3559216

In [ ]:
   # =========================================================
    # SEMI-SUPERVISED
    # =========================================================
    for prop_target in prop_target_values_s:

        # JDCOOT
        pure_source, pure_target, test_source, test_target = discrete_semisupervised_jdcoot(
                S, T, S_test, T_test,
                alpha=a,
                prop_target=prop_target
            )

        results.append({
            "repetition": repe,
            "recoding": "jdcoot",
            "learning": "semisupervised",
            "prop_source": 1,
            "prop_target": prop_target,
            "pure_source": pure_source,
            "test_source": test_source,
            "pure_target": pure_target,
            "test_target": test_target,
        })

        # COOT
        pure_source, pure_target, test_source, test_target = \
            discrete_semisupervised_coot(
                S, T, S_test, T_test,
                prop_target=prop_target
            )

        results.append({
            "repetition": repe,
            "recoding": "coot",
            "learning": "semisupervised",
            "prop_source": 1,
            "prop_target": prop_target,
            "pure_source": pure_source,
            "test_source": test_source,
            "pure_target": pure_target,
            "test_target": test_target,
        })

        # Reference
        pure_source, pure_target, test_source, test_target = discrete_semisupervised_reference(
                S, T, S_test, T_test,
                prop_target=prop_target
            )

        results.append({
            "repetition": repe,
            "recoding": "reference",
            "learning": "semisupervised",
            "prop_source": 1,
            "prop_target": prop_target,
            "pure_source": pure_source,
            "test_source": test_source,
            "pure_target": pure_target,
            "test_target": test_target,
        })

    # =========================================================
    # PARTIAL
    # =========================================================
    for prop_target in prop_target_values_p:

        # JDCOOT
        pure_source, pure_target, test_source, test_target = discrete_partial_jdcoot(
                S, T, S_test, T_test,
                alpha=a,
                prop_source=0.5,
                prop_target=prop_target
            )

        results.append({
            "repetition": repe,
            "recoding": "jdcoot",
            "learning": "partial",
            "prop_source": 0.5,
            "prop_target": prop_target,
            "pure_source": pure_source,
            "test_source": test_source,
            "pure_target": pure_target,
            "test_target": test_target,
        })

        # COOT
        pure_source, pure_target, test_source, test_target = discrete_partial_coot(
                S, T, S_test, T_test,
                prop_source=0.5,
                prop_target=prop_target
            )

        results.append({
            "repetition": repe,
            "recoding": "coot",
            "learning": "partial",
            "prop_source": 0.5,
            "prop_target": prop_target,
            "pure_source": pure_source,
            "test_source": test_source,
            "pure_target": pure_target,
            "test_target": test_target,
        })

        # Reference
        pure_source, pure_target, test_source, test_target = discrete_partial_reference(
                S, T, S_test, T_test,
                prop_source=0.5,
                prop_target=prop_target
            )

        results.append({
            "repetition": repe,
            "recoding": "reference",
            "learning": "partial",
            "prop_source": 0.5,
            "prop_target": prop_target,
            "pure_source": pure_source,
            "test_source": test_source,
            "pure_target": pure_target,
            "test_target": test_target,
        })

In [30]:
df_results = pd.DataFrame(results)
df_results

,repetition,recoding,learning,prop_source,prop_target,pure_source,test_source,pure_target,test_target
0,0,jdcoot,unsupervised,1.0,0.00,1.0000,1.000000,0.525000,0.564417
1,0,coot,unsupervised,1.0,0.00,1.0000,1.000000,0.565000,0.558282
2,0,jdcoot,semisupervised,1.0,0.01,1.0000,1.000000,0.277778,0.300613
3,0,coot,semisupervised,1.0,0.01,1.0000,1.000000,0.898990,0.815951
4,0,reference,semisupervised,1.0,0.01,1.0000,1.000000,0.447853,0.491162
5,0,jdcoot,semisupervised,1.0,0.05,1.0000,1.000000,0.819737,0.920245
6,0,coot,semisupervised,1.0,0.05,1.0000,1.000000,0.881579,0.797546
7,0,reference,semisupervised,1.0,0.05,1.0000,1.000000,0.901840,0.821053
8,0,jdcoot,semisupervised,1.0,0.10,1.0000,1.000000,0.911111,0.957055
9,0,coot,semisupervised,1.0,0.10,1.0000,1.000000,0.912500,0.730061
10,0,reference,semisupervised,1.0,0.10,1.0000,1.000000,0.944785,0.915278
11,0,jdcoot,semisupervised,1.0,0.20,1.0000,1.000000,0.915625,0.963190
12,0,coot,semisupervised,1.0,0.20,1.0000,1.000000,0.885938,0.730061
13,0,reference,semisupervised,1.0,0.20,1.0000,1.000000,0.932515,0.928125
14,0,jdcoot,semisupervised,1.0,0.40,1.0000,1.000000,0.927083,0.938650
15,0,coot,semisupervised,1.0,0.40,1.0000,1.000000,0.897917,0.840491
16,0,reference,semisupervised,1.0,0.40,1.0000,1.000000,0.938650,0.931250
17,0,jdcoot,partial,0.5,0.01,0.1150,0.668712,0.390152,0.411043
18,0,coot,partial,0.5,0.01,0.3900,0.000000,0.744949,0.779141
19,0,reference,partial,0.5,0.01,0.9225,0.914110,0.693182,0.736196
20,0,jdcoot,partial,0.5,0.05,0.0875,0.717791,0.518421,0.607362
21,0,coot,partial,0.5,0.05,0.4000,0.570552,0.860526,0.711656
22,0,reference,partial,0.5,0.05,0.9150,0.926380,0.789474,0.822086
23,0,jdcoot,partial,0.5,0.10,0.0900,0.693252,0.363889,0.539877
24,0,coot,partial,0.5,0.10,0.3525,0.773006,0.863889,0.754601
25,0,reference,partial,0.5,0.10,0.9175,0.914110,0.912500,0.926380
26,0,jdcoot,partial,0.5,0.20,0.1150,0.680982,0.526563,0.668712
27,0,coot,partial,0.5,0.20,0.4275,0.828221,0.803125,0.748466
28,0,reference,partial,0.5,0.20,0.8875,0.938650,0.931250,0.950920
29,0,jdcoot,partial,0.5,0.40,0.0775,0.552147,0.120833,0.693252
30,0,coot,partial,0.5,0.40,0.4625,0.828221,0.747917,0.889571
31,0,reference,partial,0.5,0.40,0.9125,0.926380,0.947917,0.963190

In [62]:
print(df_results)
df_summary.to_excel("results_mean.xlsx", index=False)

     repetition   recoding        learning  prop_source  prop_target  \
0             0       coot    unsupervised          1.0         0.00
1             0     jdcoot    unsupervised          1.0         0.00
2             0     jdcoot  semisupervised          1.0         0.01
3             0       coot  semisupervised          1.0         0.01
4             0  reference  semisupervised          1.0         0.01
..          ...        ...             ...          ...          ...
315           9       coot         partial          0.5         0.20
316           9  reference         partial          0.5         0.20
317           9     jdcoot         partial          0.5         0.40
318           9       coot         partial          0.5         0.40
319           9  reference         partial          0.5         0.40

     pure_source  test_source  pure_target  test_target
0       1.000000     1.000000     0.235119     0.180432
1       1.000000     1.000000     0.196429     0.137230
2       1.000000     1.000000     0.261261     0.306226
3       1.000000     1.000000     0.411411     0.376112
4       1.000000     1.000000     0.252859     0.249249
..           ...          ...          ...          ...
315     0.238095     0.783990     0.657993     0.700127
316     0.910714     0.895807     0.925651     0.926302
317     0.125000     0.730623     0.217822     0.724269
318     0.488095     0.800508     0.643564     0.803050
319     0.892857     0.879288     0.950495     0.931385

[320 rows x 9 columns]

In [56]:
import pandas as pd

df_results = pd.DataFrame(results)


df_results

df_summary = (
    df_results
    .groupby(
        ["recoding", "learning", "prop_source", "prop_target"],
        as_index=False
    )
    .agg(
        pure_source_mean=("pure_source", "mean"),
        pure_source_var=("pure_source", "var"),
        test_source_mean=("test_source", "mean"),
        test_source_var=("test_source", "var"),
        pure_target_mean=("pure_target", "mean"),
        pure_target_var=("pure_target", "var"),
        test_target_mean=("test_target", "mean"),
        test_target_var=("test_target", "var"),
    )
)

In [68]:
df_summary

,recoding,learning,prop_source,prop_target,pure_source_mean,pure_source_var,test_source_mean,test_source_var,pure_target_mean,pure_target_var,test_target_mean,test_target_var
0,coot,partial,0.5,0.01,0.223810,0.004025,0.092503,0.000319,0.476577,0.020816,0.471283,0.025641
1,coot,partial,0.5,0.05,0.398810,0.016338,0.172935,0.051504,0.632500,0.005050,0.623761,0.003843
2,coot,partial,0.5,0.10,0.346429,0.013281,0.461626,0.109756,0.645875,0.013451,0.666201,0.000688
3,coot,partial,0.5,0.20,0.455952,0.007253,0.748920,0.000550,0.578810,0.009579,0.699111,0.001020
4,coot,partial,0.5,0.40,0.447024,0.006554,0.785642,0.000724,0.559406,0.015805,0.790978,0.000396
5,coot,semisupervised,1.0,0.01,1.000000,0.000000,1.000000,0.000000,0.469069,0.011080,0.458196,0.013779
6,coot,semisupervised,1.0,0.05,1.000000,0.000000,1.000000,0.000000,0.676562,0.001474,0.668742,0.000560
7,coot,semisupervised,1.0,0.10,1.000000,0.000000,1.000000,0.000000,0.685149,0.003326,0.682211,0.000566
8,coot,semisupervised,1.0,0.20,1.000000,0.000000,1.000000,0.000000,0.688848,0.003578,0.747522,0.000451
9,coot,semisupervised,1.0,0.40,1.000000,0.000000,1.000000,0.000000,0.663861,0.006042,0.835705,0.000262
10,coot,unsupervised,1.0,0.00,1.000000,0.000000,1.000000,0.000000,0.338988,0.021271,0.337357,0.025003
11,jdcoot,partial,0.5,0.01,0.119643,0.001295,0.716137,0.001459,0.255556,0.010997,0.247776,0.005827
12,jdcoot,partial,0.5,0.05,0.129762,0.000132,0.731893,0.000502,0.444062,0.005897,0.520966,0.005301
13,jdcoot,partial,0.5,0.10,0.116071,0.000978,0.713977,0.000468,0.427063,0.005299,0.558704,0.003472
14,jdcoot,partial,0.5,0.20,0.108333,0.000510,0.705845,0.000859,0.309665,0.003821,0.616773,0.000625
15,jdcoot,partial,0.5,0.40,0.141667,0.002943,0.695299,0.001079,0.151485,0.002038,0.707624,0.000943
16,jdcoot,semisupervised,1.0,0.01,1.000000,0.000000,1.000000,0.000000,0.265165,0.006706,0.297205,0.008378
17,jdcoot,semisupervised,1.0,0.05,1.000000,0.000000,1.000000,0.000000,0.723125,0.006997,0.776112,0.011132
18,jdcoot,semisupervised,1.0,0.10,1.000000,0.000000,1.000000,0.000000,0.843894,0.000780,0.886277,0.000077
19,jdcoot,semisupervised,1.0,0.20,1.000000,0.000000,1.000000,0.000000,0.840520,0.000625,0.899111,0.000413
20,jdcoot,semisupervised,1.0,0.40,1.000000,0.000000,1.000000,0.000000,0.834653,0.001368,0.902922,0.000406
21,jdcoot,unsupervised,1.0,0.00,1.000000,0.000000,1.000000,0.000000,0.295536,0.011159,0.311690,0.012558
22,reference,partial,0.5,0.01,0.881548,0.000507,0.889072,0.000097,0.290991,0.001386,0.295553,0.002660
23,reference,partial,0.5,0.05,0.889286,0.000521,0.886150,0.000152,0.645937,0.008001,0.654511,0.006741
24,reference,partial,0.5,0.10,0.899405,0.000515,0.889199,0.000071,0.835644,0.001302,0.841677,0.001202
25,reference,partial,0.5,0.20,0.889881,0.000435,0.895934,0.000056,0.898141,0.001284,0.900508,0.000999
26,reference,partial,0.5,0.40,0.892857,0.000331,0.889708,0.000137,0.932178,0.000207,0.927573,0.000073
27,reference,semisupervised,1.0,0.01,1.000000,0.000000,1.000000,0.000000,0.252224,0.003960,0.240541,0.004704
28,reference,semisupervised,1.0,0.05,1.000000,0.000000,1.000000,0.000000,0.640025,0.008738,0.656562,0.005524
29,reference,semisupervised,1.0,0.10,1.000000,0.000000,1.000000,0.000000,0.825159,0.003468,0.826733,0.002818
30,reference,semisupervised,1.0,0.20,1.000000,0.000000,1.000000,0.000000,0.903812,0.000467,0.899257,0.001224
31,reference,semisupervised,1.0,0.40,1.000000,0.000000,1.000000,0.000000,0.928335,0.000030,0.939604,0.000462

In [57]:
df_summary.to_excel("results_mean.xlsx", index=False)

In [ ]:
alpha_grid = np.linspace(0, 1, 11)  # ex: [0.0, 0.1, ..., 1.0]


best_alpha = None
best_score = -np.inf  # ou +np.inf si MSE

numRepetitions_alpha = 5  

for a in alpha_grid:
    scores = []

    for repe in range(numRepetitions_alpha):
        XS1, yS1, XStest, yStest = get_data_2(XtotS, YtotS, nbtrain, nbtest, repe)
        XT1, yT1, XTtest, yTtest = get_data_2(XtotT, YtotT, nbtrain, nbtest, repe)

        S = pd.DataFrame(np.c_[XS1, yS1],
                         columns=[f'X{i}' for i in range(XS1.shape[1])] + ['Z'])
        T = pd.DataFrame(np.c_[XT1, yT1],
                         columns=[f'X{i}' for i in range(XT1.shape[1])] + ['Z'])
        S_test = pd.DataFrame(np.c_[XStest, yStest],
                              columns=[f'X{i}' for i in range(XStest.shape[1])] + ['Z'])
        T_test = pd.DataFrame(np.c_[XTtest, yTtest],
                              columns=[f'X{i}' for i in range(XTtest.shape[1])] + ['Z'])

        _, _, _, test_target = discrete_unsupervised_jdcoot(
            S, T, S_test, T_test, alpha=a
        )

        scores.append(test_target)

    mean_score = np.mean(scores)

    if mean_score > best_score:
        best_score = mean_score
        best_alpha = a

print("Best alpha:", best_alpha)
print("Best score:", best_score)

0.9

In [10]:
import math
results = []
numRepetitions = 10
a = 0.5

prop_target_values_s = [0.01, 0.05, 0.1, 0.2, 0.4]
prop_target_values_p = [0.01, 0.05, 0.1, 0.2, 0.4]

from jdcoot.scenario import generate_data

source=pd.DataFrame(np.concatenate((S_data[0],S_data[1].reshape(-1,1)),axis=1),columns=['X'+str(i) for i in range(S_data[0].shape[1])]+['Z'])
target=pd.DataFrame(np.concatenate((T_data[0],T_data[1].reshape(-1,1)),axis=1),columns=['X'+str(i) for i in range(T_data[0].shape[1])]+['Z'])

source.loc[:,'Z'] = source.loc[:, 'Z'] - 1
target.loc[:,'Z'] = target.loc[:, 'Z'] - 1

for repe in range(numRepetitions):
    print("num repe :", repe + 1)
    data = generate_data()
    # =========================================================
    # UNSUPERVISED
    # =========================================================

    # COOT (sans alpha)
    pure_source, pure_target, test_source, test_target = continuous_unsupervised_coot(*data)
    print(test_target)
    results.append({
        "repetition": repe,
        "recoding": "coot",
        "learning": "unsupervised",
        "prop_source": 1,
        "prop_target": 0,
        "pure_source": pure_source,
        "test_source": test_source,
        "pure_target": pure_target,
        "test_target": test_target,
    })

    # JDCOOT
    pure_source, pure_target, test_source, test_target = continuous_unsupervised_jdcoot(*data)
    print(test_target)
    results.append({
        "repetition": repe,
        "recoding": "jdcoot",
        "learning": "unsupervised",
        "prop_source": 1,
        "prop_target": 0,
        "pure_source": pure_source,
        "test_source": test_source,
        "pure_target": pure_target,
        "test_target": test_target,
    })

   

df_results = pd.DataFrame(results)


df_results

df_summary = (
    df_results
    .groupby(
        ["recoding", "learning", "prop_source", "prop_target"],
        as_index=False
    )
    .agg(
        pure_source_mean=("pure_source", "mean"),
        pure_source_var=("pure_source", "var"),
        test_source_mean=("test_source", "mean"),
        test_source_var=("test_source", "var"),
        pure_target_mean=("pure_target", "mean"),
        pure_target_var=("pure_target", "var"),
        test_target_mean=("test_target", "mean"),
        test_target_var=("test_target", "var"),
    )
)

num repe : 1
Delta:       0.2181103 	 Loss:       1.9689301
Delta:       0.0004506 	 Loss:       1.7861124
Delta:       0.0000000 	 Loss:       1.7861124
converged at iter  2
630.4723091917492
Delta:       0.2181103 	 Loss:       1.9689301
Delta:       0.0004506 	 Loss:       1.7861124
Delta:       0.0000000 	 Loss:       1.7861124
converged at iter  2
Delta: 0.21892210025777573 	  Loss: 1.9149239409673964 	 Accuracy: 583.194580078125
Delta: 0.22515493446456936 	  Loss: 1.8863706417309696 	 Accuracy: 677.1507568359375
Delta: 0.00029322244045484034 	  Loss: 1.8844867713854834 	 Accuracy: 688.86962890625
Delta: 8.101430325562712e-05 	  Loss: 1.8843320178803142 	 Accuracy: 682.8627319335938
Delta: 8.852923821495225e-05 	  Loss: 1.8843806689337081 	 Accuracy: 701.5531005859375
Delta: 0.14150326320710901 	  Loss: 1.8841414761789097 	 Accuracy: 685.6490478515625
Delta: 8.6589936591149e-05 	  Loss: 1.8842506951534017 	 Accuracy: 689.4417724609375
Delta: 7.393309179188639e-05 	  Loss: 1.8842890667671535 	 Accuracy: 686.3901977539062
Delta: 6.155957574797334e-05 	  Loss: 1.8843079713729265 	 Accuracy: 694.446533203125
Delta: 6.3824037997077e-05 	  Loss: 1.8842732434819902 	 Accuracy: 680.3484497070312
733.3253093900931
num repe : 2
Delta:       0.2181103 	 Loss:       1.9689301
Delta:       0.0004506 	 Loss:       1.7861124
Delta:       0.0000000 	 Loss:       1.7861124
converged at iter  2
630.8753849590818
Delta:       0.2181103 	 Loss:       1.9689301
Delta:       0.0004506 	 Loss:       1.7861124
Delta:       0.0000000 	 Loss:       1.7861124
converged at iter  2
Delta: 0.21892210025777573 	  Loss: 1.9149239409673964 	 Accuracy: 585.1264038085938
Delta: 0.22515873073958562 	  Loss: 1.8863617138000404 	 Accuracy: 682.3026123046875
Delta: 0.000299500133687015 	  Loss: 1.8844257445000903 	 Accuracy: 688.93603515625
Delta: 5.459987492339723e-05 	  Loss: 1.8843114915412673 	 Accuracy: 686.1513671875
Delta: 7.351381356359483e-05 	  Loss: 1.8843681718171332 	 Accuracy: 690.4107055664062
Delta: 4.587129982611542e-05 	  Loss: 1.8843658194790651 	 Accuracy: 686.5765380859375
Delta: 6.345698187336809e-05 	  Loss: 1.8844717468873284 	 Accuracy: 689.7852172851562
Delta: 9.07965985675036e-05 	  Loss: 1.884424393295665 	 Accuracy: 698.2265625
Delta: 6.193421351439678e-05 	  Loss: 1.8843099069738751 	 Accuracy: 690.5344848632812
Delta: 0.00011476770594736813 	  Loss: 1.8843136281416246 	 Accuracy: 686.3825073242188
744.0935200827448
num repe : 3
Delta:       0.2181103 	 Loss:       1.9689301
Delta:       0.0004506 	 Loss:       1.7861124
Delta:       0.0000000 	 Loss:       1.7861124
converged at iter  2
630.1446886151749
Delta:       0.2181103 	 Loss:       1.9689301
Delta:       0.0004506 	 Loss:       1.7861124
Delta:       0.0000000 	 Loss:       1.7861124
converged at iter  2
Delta: 0.21892210025777573 	  Loss: 1.9149239409673964 	 Accuracy: 579.8825073242188
Delta: 0.22514222469867023 	  Loss: 1.8864885938749738 	 Accuracy: 678.4266357421875
Delta: 0.00030077343279150197 	  Loss: 1.8844566155499494 	 Accuracy: 691.635009765625
Delta: 6.451070534373568e-05 	  Loss: 1.884340496110858 	 Accuracy: 677.733642578125
Delta: 9.224247124290836e-05 	  Loss: 1.884338272179791 	 Accuracy: 691.2761840820312
Delta: 8.853957864665578e-05 	  Loss: 1.8842685318017471 	 Accuracy: 691.4813842773438
Delta: 8.993804495915611e-05 	  Loss: 1.8842780438400597 	 Accuracy: 679.3960571289062
Delta: 7.928881887317755e-05 	  Loss: 1.8844412282194112 	 Accuracy: 689.1959228515625
Delta: 6.379587517271545e-05 	  Loss: 1.8843493117880996 	 Accuracy: 677.713623046875
Delta: 6.698393939257277e-05 	  Loss: 1.8844826698483923 	 Accuracy: 682.4413452148438
743.9615264226018
num repe : 4
Delta:       0.2181103 	 Loss:       1.9689301
Delta:       0.0004506 	 Loss:       1.7861124
Delta:       0.0000000 	 Loss:       1.7861124
converged at iter  2
631.1987223071557
Delta:       0.2181103 	 Loss:       1.9689301
Delta:       0.0004506 	 Loss:       1.7861124
Delta:       0.0000000 	 Loss:       1.7861124
converged at iter  2
Delta: 0.21892210025777573 	  Loss: 1.9149239409673964 	 Accuracy: 581.0992431640625
Delta: 0.22514049719546686 	  Loss: 1.8865805853326534 	 Accuracy: 676.941650390625
Delta: 0.0002995464794177084 	  Loss: 1.884687211924583 	 Accuracy: 694.6455078125
Delta: 9.122856267325127e-05 	  Loss: 1.8844944223069748 	 Accuracy: 678.1643676757812
Delta: 8.48686877614579e-05 	  Loss: 1.884568547055054 	 Accuracy: 688.04443359375
Delta: 8.301901592291034e-05 	  Loss: 1.8843711888825567 	 Accuracy: 687.4323120117188
Delta: 8.335032864037271e-05 	  Loss: 1.8843630275040808 	 Accuracy: 684.149658203125
Delta: 6.372025342957672e-05 	  Loss: 1.8844669679475587 	 Accuracy: 684.5308837890625
Delta: 8.606554429118382e-05 	  Loss: 1.884514208766348 	 Accuracy: 688.0646362304688
Delta: 5.6846488839117125e-05 	  Loss: 1.8844076804919414 	 Accuracy: 678.625
735.0780967045969
num repe : 5
Delta:       0.2181103 	 Loss:       1.9689301
Delta:       0.0004506 	 Loss:       1.7861124
Delta:       0.0000000 	 Loss:       1.7861124
converged at iter  2
631.6853879899633
Delta:       0.2181103 	 Loss:       1.9689301
Delta:       0.0004506 	 Loss:       1.7861124
Delta:       0.0000000 	 Loss:       1.7861124
converged at iter  2
Delta: 0.21892210025777573 	  Loss: 1.9149239409673964 	 Accuracy: 580.317626953125
Delta: 0.22513785831955474 	  Loss: 1.8865244159732095 	 Accuracy: 679.7738037109375
Delta: 0.0003104739866469689 	  Loss: 1.8845002109916835 	 Accuracy: 674.6715698242188
Delta: 9.198373429474547e-05 	  Loss: 1.8845563573524604 	 Accuracy: 679.7293090820312
Delta: 0.00010614424768122471 	  Loss: 1.8846063166996962 	 Accuracy: 682.4448852539062
Delta: 6.806642899520791e-05 	  Loss: 1.8846191058722568 	 Accuracy: 672.9352416992188
Delta: 8.130300265024861e-05 	  Loss: 1.8845875548211104 	 Accuracy: 674.7318725585938
Delta: 7.186950767474049e-05 	  Loss: 1.8845950654773305 	 Accuracy: 674.5614013671875
Delta: 0.00010261203276804376 	  Loss: 1.8845837971668202 	 Accuracy: 678.6738891601562
Delta: 4.67277002748303e-05 	  Loss: 1.884612528365675 	 Accuracy: 684.337890625
745.330165396582
num repe : 6
Delta:       0.2181103 	 Loss:       1.9689301
Delta:       0.0004506 	 Loss:       1.7861124
Delta:       0.0000000 	 Loss:       1.7861124
converged at iter  2
631.7171431210544
Delta:       0.2181103 	 Loss:       1.9689301
Delta:       0.0004506 	 Loss:       1.7861124
Delta:       0.0000000 	 Loss:       1.7861124
converged at iter  2
Delta: 0.21892210025777573 	  Loss: 1.9149239409673964 	 Accuracy: 583.5454711914062
Delta: 0.2251488278175496 	  Loss: 1.886445606591662 	 Accuracy: 681.4209594726562
Delta: 0.00029576057960124753 	  Loss: 1.884595423217137 	 Accuracy: 683.1985473632812
Delta: 8.828395535345686e-05 	  Loss: 1.8844649188377047 	 Accuracy: 692.7568359375
Delta: 9.930074738422531e-05 	  Loss: 1.8841666154222692 	 Accuracy: 692.1456909179688
Delta: 6.46873440827861e-05 	  Loss: 1.8840996528219698 	 Accuracy: 690.395751953125
Delta: 4.434776576765569e-05 	  Loss: 1.884123563559481 	 Accuracy: 684.8262329101562
Delta: 8.787908539087307e-05 	  Loss: 1.8842419166680833 	 Accuracy: 688.0776977539062
Delta: 5.473379303002342e-05 	  Loss: 1.8843071982253727 	 Accuracy: 686.8931884765625
Delta: 8.022535365111338e-05 	  Loss: 1.8841606118707002 	 Accuracy: 679.5762329101562
733.3754547858169
num repe : 7
Delta:       0.2181103 	 Loss:       1.9689301
Delta:       0.0004506 	 Loss:       1.7861124
Delta:       0.0000000 	 Loss:       1.7861124
converged at iter  2
629.8259984805103
Delta:       0.2181103 	 Loss:       1.9689301
Delta:       0.0004506 	 Loss:       1.7861124
Delta:       0.0000000 	 Loss:       1.7861124
converged at iter  2
Delta: 0.21892210025777573 	  Loss: 1.9149239409673964 	 Accuracy: 584.2667236328125
Delta: 0.22515142437911664 	  Loss: 1.8863205238229308 	 Accuracy: 682.9679565429688
Delta: 0.0002904375000787463 	  Loss: 1.8844272324228628 	 Accuracy: 696.8092651367188
Delta: 7.5662080973521e-05 	  Loss: 1.8843631752953058 	 Accuracy: 688.0350952148438
Delta: 7.806161314685475e-05 	  Loss: 1.884448750142598 	 Accuracy: 687.6248168945312
Delta: 7.648455914854734e-05 	  Loss: 1.8843969697368725 	 Accuracy: 691.3101196289062
Delta: 9.035979678329195e-05 	  Loss: 1.8842919237889857 	 Accuracy: 684.1235961914062
Delta: 6.793099854962163e-05 	  Loss: 1.8843570281467017 	 Accuracy: 688.7764282226562
Delta: 4.439870062495567e-05 	  Loss: 1.8843357354468968 	 Accuracy: 692.653564453125
Delta: 8.894002223865219e-05 	  Loss: 1.8844434202987639 	 Accuracy: 695.1509399414062
753.604744837144
num repe : 8
Delta:       0.2181103 	 Loss:       1.9689301
Delta:       0.0004506 	 Loss:       1.7861124
Delta:       0.0000000 	 Loss:       1.7861124
converged at iter  2
631.236286205721
Delta:       0.2181103 	 Loss:       1.9689301
Delta:       0.0004506 	 Loss:       1.7861124
Delta:       0.0000000 	 Loss:       1.7861124
converged at iter  2
Delta: 0.21892210025777573 	  Loss: 1.9149239409673964 	 Accuracy: 581.1766357421875
Delta: 0.225139762118138 	  Loss: 1.8864850816103798 	 Accuracy: 677.04052734375
Delta: 0.00029777940278756456 	  Loss: 1.8845036180931092 	 Accuracy: 689.8047485351562
Delta: 0.00012104979993940162 	  Loss: 1.8842639308254765 	 Accuracy: 688.934326171875
Delta: 7.200440191153594e-05 	  Loss: 1.884317441501216 	 Accuracy: 683.3609619140625
Delta: 7.028051239049559e-05 	  Loss: 1.884320114317341 	 Accuracy: 685.79736328125
Delta: 5.645956394529926e-05 	  Loss: 1.8842296096720976 	 Accuracy: 690.1190795898438
Delta: 6.88312486271056e-05 	  Loss: 1.8842315387619881 	 Accuracy: 685.711181640625
Delta: 7.266837315116496e-05 	  Loss: 1.8843021655487227 	 Accuracy: 690.7537231445312
Delta: 6.31896147791461e-05 	  Loss: 1.8843450500709285 	 Accuracy: 677.221923828125
733.592947987633
num repe : 9
Delta:       0.2181103 	 Loss:       1.9689301
Delta:       0.0004506 	 Loss:       1.7861124
Delta:       0.0000000 	 Loss:       1.7861124
converged at iter  2
629.7894344453441
Delta:       0.2181103 	 Loss:       1.9689301
Delta:       0.0004506 	 Loss:       1.7861124
Delta:       0.0000000 	 Loss:       1.7861124
converged at iter  2
Delta: 0.21892210025777573 	  Loss: 1.9149239409673964 	 Accuracy: 582.9486083984375
Delta: 0.22515436398777489 	  Loss: 1.8864931184044536 	 Accuracy: 679.1475219726562
Delta: 0.00030279569053070875 	  Loss: 1.8845233363905676 	 Accuracy: 686.9678955078125
Delta: 6.848624730017812e-05 	  Loss: 1.8844025405489881 	 Accuracy: 682.9223022460938
Delta: 5.704001147371693e-05 	  Loss: 1.8844357228021478 	 Accuracy: 681.529052734375
Delta: 5.874833973689835e-05 	  Loss: 1.8844658426959788 	 Accuracy: 685.639892578125
Delta: 6.97061505861991e-05 	  Loss: 1.8843897517360677 	 Accuracy: 684.7158203125
Delta: 6.017283915121568e-05 	  Loss: 1.884474301673892 	 Accuracy: 684.0198974609375
Delta: 6.493836759068687e-05 	  Loss: 1.8845036311136147 	 Accuracy: 679.890625
Delta: 7.458603656938547e-05 	  Loss: 1.88459293758816 	 Accuracy: 678.7509155273438
735.5641990541623
num repe : 10
Delta:       0.2181103 	 Loss:       1.9689301
Delta:       0.0004506 	 Loss:       1.7861124
Delta:       0.0000000 	 Loss:       1.7861124
converged at iter  2
630.624042339086
Delta:       0.2181103 	 Loss:       1.9689301
Delta:       0.0004506 	 Loss:       1.7861124
Delta:       0.0000000 	 Loss:       1.7861124
converged at iter  2
Delta: 0.21892210025777573 	  Loss: 1.9149239409673964 	 Accuracy: 581.003173828125
Delta: 0.22514305792677575 	  Loss: 1.8864791611823888 	 Accuracy: 680.7308349609375
Delta: 0.00031159103336992553 	  Loss: 1.884387387263955 	 Accuracy: 684.8783569335938
Delta: 9.860605368704237e-05 	  Loss: 1.8842746408774427 	 Accuracy: 673.9585571289062
Delta: 6.497999540406714e-05 	  Loss: 1.8844469021053345 	 Accuracy: 674.1127319335938
Delta: 7.601568760525513e-05 	  Loss: 1.8844652730509832 	 Accuracy: 682.427734375
Delta: 0.10008650231163074 	  Loss: 1.884230236398297 	 Accuracy: 682.97412109375
Delta: 7.126004861382823e-05 	  Loss: 1.8841964023015798 	 Accuracy: 679.23486328125
Delta: 6.369742710224258e-05 	  Loss: 1.8842393011690444 	 Accuracy: 677.961181640625
Delta: 7.003130044131307e-05 	  Loss: 1.8842955645002177 	 Accuracy: 672.94189453125
729.9225002253538

In [11]:
df_summary

,recoding,learning,prop_source,prop_target,pure_source_mean,pure_source_var,test_source_mean,test_source_var,pure_target_mean,pure_target_var,test_target_mean,test_target_var
0,coot,unsupervised,1,0,0.0,0.0,0.000000,0.000000,694.654605,0.000000,630.756940,0.499914
1,jdcoot,unsupervised,1,0,0.0,0.0,412.270749,0.101959,681.577705,36.828651,738.784846,56.236471